### ISSUE TITLE
Hi, this isn't an issue - I just wanted to say thank you for creating this library. It's amazingly well-documented and works perfectly

### ISSUE THREAD

**Issue by ckoshka** [rany2/edge-tts#10]
Also – I was thinking of asking for your permission to port this to Typescript and Rust but I noticed there were a couple of secrets being used in the request headers. Would those still be safe to use in a ported version?

**Comment by rany2** [comment]
@ckoshka Hi, there is no need for permission. Also the secrets are just the ones that are used by the Edge browser.

**Comment by KrystofS** [comment]
@rany2 I was looking myself into this. However, I haven't found any documentation for the API. Did you managed to find any or you just analysed the packets sent by Edge?

**Comment by rany2** [comment]
@KrystofS Hi, there is no documentation for the API. I analyzed the packets from the Edge Browser and then messed around with the API for a bit.

**Comment by jppg** [comment]
Yes, I totally agree, for me this package is amazing.
Thank you mate
