### ISSUE TITLE
could you please provide an instant sound play demo

### ISSUE THREAD

**Issue by Animath3099** [rany2/edge-tts#100]
Thank you very much for this project. 
I wonder if you can provide a short python script to show how to play the sound without saving it to a local mp3 file first. 
Thank you !

**Comment by rany2** [comment]
All the audio playback libraries I know eventually would put the data on disk, one way or the other even when you didn't explicitly ask for it. Really just putting it in tmpfs should be OK, I'm not sure why everyone has an issue with that.

Also the data received from server is either WebM or MP3 and both would need to be converted before being sent to the audio server, and the only ways available to convert these to formats supported by the audio server would require you to put the data in a file.

**Comment by lonngxiang** [comment]
same, not to save disk, how to save memeoy then read to play?
