### ISSUE TITLE
How to use this api in Node service

### ISSUE THREAD

**Issue by bzzz1023** [rany2/edge-tts#102]
I want to use it create a web server with node.
appreciate your reply

**Comment by bzzz1023** [comment]
i have made it in node with child_process module.
by the way I also have a question，i see someone said he execute this command after about forty times and then start to fail, so is this the reason for that one ip use it too many times?

**Comment by rany2** [comment]
@bzzz1023 He was executing that command 40 times **_in parallel_**. Realistically if you aren't using it in a very spammy way it shouldn't be an issue, regardless I haven't had an issue running it in parallel more than a hundred times, so I guess it depends on the server. Worst case, you could try to rerun the command with some exponential backoff if you really wanted to

**Comment by bzzz1023** [comment]
so appreciate you reply
btw what is the spammy way to use it ,could you please make some examples?

**Comment by rany2** [comment]
by spammy, I mean running having more than 40 connections in parallel to the TTS server

**Comment by bzzz1023** [comment]
i see , actually i did not learn python before 
so, with this library ,every time i execute the command and  will it automatically end the connection with TTS ? 
if it is, i just need to record the max connection at same time

**Comment by rany2** [comment]
@bzzz1023 yes it does

**Comment by bzzz1023** [comment]
cool, thank you very much!
