### ISSUE TITLE
Make edge-playback more instantaneous for large text

### ISSUE THREAD

**Issue by rany2** [rany2/edge-tts#103]
This was done in the past however when subtitles were added this stopped being possible as easily.

Split text into chunks for subtitles to work properly for edge-playback and to provide instantaneous playback.

**Comment by rany2** [comment]
Why? Because I want to integrate it with https://github.com/wustho/epy but I don't want to wait for ages for the playback.

**Comment by TheNicestDev** [comment]
Yes absolutely. Couldn't you have it read everything live so that you don't need any temporary files at all?

**Comment by rany2** [comment]
I've done that before but had to stop doing that so the subtitle generation works.

**Comment by TheNicestDev** [comment]
Can you maybe make it optional?

**Comment by CheerfulPianissimo** [comment]
FWIW ` edge-tts -t "text here" | mpv - ` starts playing audio instantaneously independent of text size.

**Comment by rany2** [comment]
@CheerfulPianissimo that's how the edge-playback command used to work before adding subtitles support :)

**Comment by nazdridoy** [comment]
> Why? Because I want to integrate it with https://github.com/wustho/epy but I don't want to wait for ages for the playback.

any progress? i get "TimeoutError" and partial audio (1-9 min at random)

**Comment by rany2** [comment]
> > Why? Because I want to integrate it with https://github.com/wustho/epy but I don't want to wait for ages for the playback.
> 
> any progress? i get "TimeoutError" and partial audio (1-9 min at random)

If you're on Linux/Mac, you could do `edge-tts --text "$@" | mpv -` (or Windows equivalent); it will do it immediately. Unfortunately, the partial audio is this issue: https://github.com/rany2/edge-tts/issues/190

**Comment by rany2** [comment]
Not possible due to subtitles needing to be generated properly with offset compensation. If someone doesn't care about subtitles, they can just pipe directly to mpv as mentioned above.
