### ISSUE TITLE
How to change the file save address

### ISSUE THREAD

**Issue by bzzz1023** [rany2/edge-tts#104]
thank you!

**Comment by rany2** [comment]
I'm sorry but I don't understand, it is not defaulted to anything? Are you asking about how to change the generated mp3 file name? If yes, it is `edge-tts --text "Some generated text" --write-media >>your mp3 filename<<`

**Comment by bzzz1023** [comment]
I want to save it to the file directory I appointed

**Comment by rany2** [comment]
Just add the file directory to the `--write-media` path. So `edge-tts --text "Some generated text" --write-media your_folder/gen.mp3`

**Comment by bzzz1023** [comment]
it works
thank you very much!!!
