### ISSUE TITLE
1.How to insert pauses in text？  2. How to install more voice pack to obtain more characters？ thanks !

### ISSUE THREAD

**Issue by sweetsmile888** [rany2/edge-tts#105]

**Comment by rany2** [comment]
> How to insert pauses in text？

You could add `...` or new paragraphs in the text to have pauses. You cannot use custom SSML to accomplish that.

 > How to install more voice pack to obtain more characters？

What do you mean by "more characters?" Do you mean additional voices?

**Comment by sweetsmile888** [comment]
> > How to insert pauses in text？
> 
> You could add `...` or new paragraphs in the text to have pauses. You cannot use custom SSML to accomplish that.
> 
> > How to install more voice pack to obtain more characters？
> 
> What do you mean by "more characters?" Do you mean additional voices?

yes,defualt voices is too less,can I install more?

**Comment by sweetsmile888** [comment]
> > How to insert pauses in text？
> 
> You could add `...` or new paragraphs in the text to have pauses. You cannot use custom SSML to accomplish that.

I have add `...` or new paragraphs in the text,but it have no obvious effect, actually, I want to control the pauses time,because the default pauses time is too short  by Punctuation

**Comment by rany2** [comment]
You can't unfortunately. Only basic ways like creating paragraphs and `...` could be used, no custom SSML is allowed otherwise the request is blocked.
