### ISSUE TITLE
To add a stress manually

### ISSUE THREAD

**Issue by katya-bateeva** [rany2/edge-tts#109]
Is it possible to add a stress to a word manually? I've looked through the code and it seems that there is no such option in edge-tts.
E.g. the text is "I was so content with their content". The word "content" can has different stress depending on the meaning of the word: cOntent or contEnt.

**Comment by rany2** [comment]
You can't, Microsoft blocks any custom SSML so this feature cannot be implemented. You might want to try and play around with the text input by spelling `content` in some different way but you can't do anything beyond that. The service will block the request if you use the stress SSML tag.

**Comment by katya-bateeva** [comment]
@rany2 , thank you for sharing this information!
