### ISSUE TITLE
add an option to use api key?

### ISSUE THREAD

**Issue by iorilu** [rany2/edge-tts#116]
it's better to  have two options , with key and without key

since if use a key , there are more voice names for selection , and maybe better speed and less connection limit, anyway , for now the key is mostly free.

**Comment by rany2** [comment]
@iorilu Could you elaborate on this a bit more? What do you mean by "with/without key"? You mean using an azure cognitive services API key?

**Comment by iorilu** [comment]
> @iorilu Could you elaborate on this a bit more? What do you mean by "with/without key"? You mean using an azure cognitive services API key?

yes, since I found the voice provided by edge is  a lot less compare to the whole list.

**Comment by rany2** [comment]
If you are going to pay for azure cognitive services use official SDK not this.
