### ISSUE TITLE
无法在带有参数"style" or "styledegree"的情况下正常工作

### ISSUE THREAD

**Issue by georgezhao2010** [rany2/edge-tts#12]
之前是可以的，不知道从何时起，在带有"style"和"styledegree"的情况下，edge-tts无法生成mp3文件，也就是说，现在生成的XML文件中如果包含了<mstts:express-as>，则不能生成mp3文件。不知道是不是微软的锅。

**Comment by rany2** [comment]
Seems like Microsoft took notice, Microsoft blocked custom SSML. Nothing I can do about it unfortunately :(

**Comment by rany2** [comment]
More things that are now blocked:

* any usage of `mstts:*`
* any usage of multiple voices in the SSML

Probably a lot more like using contour, etc

**Comment by rany2** [comment]
Check comment on https://github.com/hasscc/hass-edge-tts/issues/8#issuecomment-1159784776.

**Comment by rany2** [comment]
custom SSML support has been removed https://github.com/rany2/edge-tts/commit/68a9e191d7b00c424fe137390254a7a5c8e41db7
