### ISSUE TITLE
fil-PH-AngeloNeural  voice invalid

### ISSUE THREAD

**Issue by PLL-L** [rany2/edge-tts#121]
raise ValueError(f"Invalid voice '{voice}'.")
ValueError: Invalid voice 'fil-PH-AngeloNeural '.

Source code:
match = re.match(r"^([a-z]{2})-([A-Z]{2})-(.+Neural)$", voice)

Update code:
match = re.match(r"^([a-z]{2,3})-([A-Z]{2})-(.+Neural)$", voice)

![image](https://github.com/rany2/edge-tts/assets/69779037/8e74c6a8-1715-4d62-a157-034d562d1038)

**Comment by rany2** [comment]
Your edge-tts is old, this was already fixed a couple months ago.
