### ISSUE TITLE
Can edge-tts execute multiple tts tasks asynchronously for microsoft free users now?

### ISSUE THREAD

**Issue by homerlau** [rany2/edge-tts#122]
First of all, thank you very much for your efforts.
Can edge-tts execute multiple tts tasks asynchronously now? About 2 days ago, I am able to execute 20 tts tasks at the same time using your code (edge_tts.Communicate and submaker.generate_subs), in just several seconds. But after that, When I run the program again, I find that the program executes the next tts until the previous one is done. That it to say, edge-tts can only execute one tts task at the same time. I suppose edge-tts is asynchronously executable, but the issue is, does Microsoft support asynchronous execution of tts now? Did microsoft revise the terms about executing tts asynchronously for free users? Or, would you give me an example, how to execute several tts tasks at the same time as a microsoft free user?
Thanks again.

**Comment by rany2** [comment]
I'm not too sure, but the latest time I've tried it (about a month ago) there was no such issue. I assume rate limits might change depending on their conditions, load, etc.
