### ISSUE TITLE
Subtitles split

### ISSUE THREAD

**Issue by Tendaliu** [rany2/edge-tts#126]
The segmentation of the subtitles is not very reasonable, a sentence is often cut off in the middle. Can you solve this problem?

**Comment by rany2** [comment]
Yes, it is a solvable problem. Just haven't had the time to do

**Comment by rany2** [comment]
I'll most likely use some SRT generation library instead of my "homegrown" solution to save time.

**Comment by rany2** [comment]
Duplicate of https://github.com/rany2/edge-tts/issues/118
