### ISSUE TITLE
If the API's parallel limitation is primarily based on IP addresses?

### ISSUE THREAD

**Issue by hyh957947142** [rany2/edge-tts#128]
Hello, author! First of all, I want to express my gratitude for creating this lib. It is incredibly useful. The stability, parallelism, and ease of use have exceeded my expectations.

Currently, I am planning to integrate it into my website application. I would like to understand if the API's parallel limitation is primarily based on IP addresses. If I use multiple proxy IPs, would it be possible to reduce the impact of the parallel limitation?

Thank you!

**Comment by rany2** [comment]
I believe so, in fact it seems to also work fine with Tor IPs; so the ISP behind proxy IPs should not matter either.

**Comment by goldenNormal** [comment]
Thank you for your reply!
