### ISSUE TITLE
ssl How to handle it

### ISSUE THREAD

**Issue by wupanfeng1985** [rany2/edge-tts#129]
raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host speech.platform.bing.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

**Comment by codecola115** [comment]
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

**Comment by rany2** [comment]
@codecola115 Thank you so much, I see it's an issue with Mac OS then. I'll add certifi as a dependency and use it as trust store.
