### ISSUE TITLE
Cannot close a running event loop

### ISSUE THREAD

**Issue by amirreza1307** [rany2/edge-tts#132]
hi i use basic_generation in google colab but i get this error

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-2-4ab2879ed0d2>](https://localhost:8080/#) in <cell line: 22>()
     24     try:
---> 25         loop.run_until_complete(amain())
     26     finally:

4 frames
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
[/usr/lib/python3.10/asyncio/selector_events.py](https://localhost:8080/#) in close(self)
     82     def close(self):
     83         if self.is_running():
---> 84             raise RuntimeError("Cannot close a running event loop")
     85         if self.is_closed():
     86             return

RuntimeError: Cannot close a running event loop

why?

**Comment by rany2** [comment]
You don't need to create a new event loop, instead of https://github.com/rany2/edge-tts/blob/master/examples/basic_generation.py#L23C1-L27 just do `await amain()`
