### ISSUE TITLE
Ignore SSL Verification for HTTPS Proxies

### ISSUE THREAD

**Issue by lonngxiang** [rany2/edge-tts#133]
HTTPS proxies https://127.0.0.1:10809 are not supported, ignoring

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:997)

**Comment by rany2** [comment]
I'll have to add an option to disable SSL verification for HTTPS proxies.

**Comment by rany2** [comment]
Actually the error you shared is not related to certificate verification, so the fix I was thinking of wouldn't have worked in the first place. As it seems complicated to disable certificate verification and/or to allow your proxy to function, I will close as won't fix.
