### ISSUE TITLE
add voice-style support.

### ISSUE THREAD

**Issue by dioxide** [rany2/edge-tts#135]
Is it possible to add "voice-style" support  ? 

For example: 
Voice: zh-CN-YunxiNeural
Styles: ['narration-relaxed', 'embarrassed', 'fearful', 'cheerful', 'disgruntled', 'serious', #'angry', 'sad', 'depressed', 'chat', 'assistant', 'newscast']

Maybe in parameter like this:
edge-playback --style= newscast --voice zh-CN-YunxiNeural --text "Hello!"

**Comment by rany2** [comment]
Setting voice-style is not possible anymore. Previously this package had full feature parity with Azure Cognitive Services but now the server refuses to generate audio if you're using features/voices/etc not directly available from the Edge browser. See https://github.com/rany2/edge-tts#custom-ssml
