### ISSUE TITLE
text breaks

### ISSUE THREAD

**Issue by moha-abdi** [rany2/edge-tts#136]
is it possible to somehow add text pauses. may be using [pause] or something

**Comment by rany2** [comment]
Same issue as https://github.com/rany2/edge-tts/issues/58

**Comment by moha-abdi** [comment]
If someone is searching for how to pause with edge_tts I just wrote a custom Class that uses edge_tts and handles pause times as the edge_tts no longer support custom SSML.

here is the link to it: [https://gist.github.com/moha-abdi/8ddbcb206c38f592c65ada1e5479f2bf](url)

**Comment by omega3** [comment]
@moha-abdi
Please tell me how to use it? I need 3 second pause / silence between sentences. What is the command to run it in Linux Terminal? How to merge it with this command: 
`edge-tts -f sample.txt --write-media output.mp3`

How to point to txt file and how to edit file to make it work?
