### ISSUE TITLE
Can only use one voice per gender

### ISSUE THREAD

**Issue by Jay54520** [rany2/edge-tts#14]
Version: 5.0.0
Many languages can only use one voice per gender, for example, Chinese femal can only use `zh-CN-XiaoxiaoNeural` but can't use `zh-CN-XiaoxuanNeural`. Chinese male can only use `zh-CN-YunyangNeural`.

```bash
# Success
edge-playback --text "Hello, world!" --voice zh-CN-XiaoxiaoNeural
# Fail
$ edge-playback --text "Hello, world!" --voice zh-CN-XiaoxuanNeural

Media file: /tmp/tmpy3dtrfg6
Subtitle file: /tmp/tmphm0_zpim

Failed to recognize file format.


Exiting... (Errors when loading file)
```

**Comment by rany2** [comment]
@Jay54520 I don't understand what you're trying to do

**Comment by Jay54520** [comment]
> @Jay54520 I don't understand what you're trying to do
> 
> Edit: I think a code example or step by step instructions on what you're trying to do but failing at would help

I update above post by using commnad line instead of Python code so you can run it directly.

**Comment by rany2** [comment]
@Jay54520 you got the voices wrong, there is no `zh-CN-XiaoxuanNeural`. Use `edge-tts --list-voices` to get a list of voices:

```
Name: Microsoft Server Speech Text to Speech Voice (zh-HK, HiuMaanNeural)
ShortName: zh-HK-HiuMaanNeural
Gender: Female
Locale: zh-HK

Name: Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoxiaoNeural)
ShortName: zh-CN-XiaoxiaoNeural
Gender: Female
Locale: zh-CN

Name: Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoyiNeural)
ShortName: zh-CN-XiaoyiNeural
Gender: Female
Locale: zh-CN

Name: Microsoft Server Speech Text to Speech Voice (zh-CN, YunjianNeural)
ShortName: zh-CN-YunjianNeural
Gender: Male
Locale: zh-CN

Name: Microsoft Server Speech Text to Speech Voice (zh-CN, YunxiNeural)
ShortName: zh-CN-YunxiNeural
Gender: Male
Locale: zh-CN

Name: Microsoft Server Speech Text to Speech Voice (zh-CN, YunxiaNeural)
ShortName: zh-CN-YunxiaNeural
Gender: Male
Locale: zh-CN

Name: Microsoft Server Speech Text to Speech Voice (zh-CN, YunyangNeural)
ShortName: zh-CN-YunyangNeural
Gender: Male
Locale: zh-CN

Name: Microsoft Server Speech Text to Speech Voice (zh-TW, HsiaoChenNeural)
ShortName: zh-TW-HsiaoChenNeural
Gender: Female
Locale: zh-TW
```

**Comment by Jay54520** [comment]
Voices in your list still fails
```bash
$ edge-playback --text "Hello, world!" --voice XiaoyiNeural

Media file: /tmp/tmp72ctsjg1
Subtitle file: /tmp/tmpwvk4zsnv

Failed to recognize file format.


Exiting... (Errors when loading file)

$ edge-playback --text "Hello, world!" --voice YunxiaNeural

Media file: /tmp/tmp9m1s7yzv
Subtitle file: /tmp/tmphlphmh16

Failed to recognize file format.


Exiting... (Errors when loading file)
```

**Comment by rany2** [comment]
@Jay54520 This is for the voices available in Microsoft Edge. Previously this library was able to access everything in Azure Cognitive Services but now Microsoft cracked down and it's limited to only the functions available in Edge.

**Comment by Jay54520** [comment]
> @Jay54520 This is for the voices available in Microsoft Edge. Previously this library was able to access everything in Azure Cognitive Services but now Microsoft cracked down and it's limited to only the functions available in Edge.

Got it. I thought this project only lacks [Custom SSML](https://github.com/rany2/edge-tts#custom-ssml) before, now I know it can only achive funcitons in Edge.
