### ISSUE TITLE
Subtitle Sync Issue with Playback Speed Adjustment

### ISSUE THREAD

**Issue by Nicolas-Gong** [rany2/edge-tts#141]
If the playback speed is set, for example, at +20%, there will be a time delay between a 1-hour and 4-minute audio and subtitles. The subtitles will end up being one second behind the audio. Is there a way to fix this issue? I have tried playing without adjusting the speed, and in that case, the subtitles sync perfectly with the audio, but it doesn't work when I accelerate the playback.

**Comment by rany2** [comment]
So you're basically saying that after the 1h:4m mark it starts to desync?

**Comment by rany2** [comment]
Does this issue still happen? It seems fixed for me.

**Comment by rany2** [comment]
Reopen if the current fix isn't adequate.
