### ISSUE TITLE
Can we use additional voices/custom Voice?

### ISSUE THREAD

**Issue by HSultankhan** [rany2/edge-tts#151]
Hello, I was wondering if its possible to include my own voice in this? Is it possible? 

If yes, Please tell how to?

**Comment by rany2** [comment]
That's not possible, there's no way this could be done with the APIs we're using. Even if it is possible with Azure's offerings, the endpoints this library uses are restricted by Microsoft to only the features needed to work with Edge Browser. If you need anything more advanced I guess you'll need to look elsewhere.
