### ISSUE TITLE
any support for WAV output? (python seems to support wav playback natively)

### ISSUE THREAD

**Issue by RaSan147** [rany2/edge-tts#161]
Is there any flag to update the format?

https://github.com/rany2/edge-tts/blob/5b7add93b9f64c27b5ed7138c30a1a4f25ba6a9d/src/edge_tts/communicate.py#L364

Value reference: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-audio-content-creation#export-tuned-audio

will these values work?

**Comment by rany2** [comment]
It doesn't unfortunately. Edge used to also use webm format but that seems to no longer work either, the server just doesn't return anything. That's why it's hardcoded now.
