### ISSUE TITLE
GUI request

### ISSUE THREAD

**Issue by unifirer** [rany2/edge-tts#164]
with all the voices and options, can we please have a GUI

thank you

**Comment by suxinde2009** [comment]
+1

**Comment by AndresRivas0** [comment]
use this web ui

[Microsoft text to speech downloader](https://www.microsoft-tts-downloader.com/tts)

**Comment by schr-0dinger** [comment]
> with all the voices and options, can we please have a GUI
> 
> thank you

Yes, check out the [GUI version](https://github.com/schr-0dinger/edge_tts_gui) of this project I created. Thank you @rany2

**Comment by KingDanx** [comment]
I made a GUI with Electron.  It doesn't have all of the features such as pitch, etc., but you can select the voice you want, preview the text and save the file.  Right now it's Windows only.  You can find it [here](https://github.com/KingDanx/edge-tts-electron/releases/tag/release).

![image](https://github.com/user-attachments/assets/caa39a83-1a18-409d-a855-2d43beeaf61a)

**Comment by rany2** [comment]
There are a lot of GUIs for edge-tts these days.
