### ISSUE TITLE
Audio stream

### ISSUE THREAD

**Issue by purkylin** [rany2/edge-tts#17]
HI, How to deal with audio stream? It worked well earlier, but that don't work any more now.

```python
# TODO: implement this:
"""
X-RequestId:xxxxxxxxxxxxxxxxxxxxxxxxx
Content-Type:application/json; charset=utf-8
Path:response
{"context":{"serviceTag":"yyyyyyyyyyyyyyyyyyy"},"audio":{"type":"inline","streamId":"zzzzzzzzzzzzzzzzz"}}

**Comment by rany2** [comment]
Are you using custom SAML? update to the latest version or avoid anything that's no longer  allowed in latest.

**Comment by purkylin** [comment]
This is my request, should be custom SSML
```
X-RequestId:9CEB1BE7ED784A90AFD419175FF6BA89
Content-Type:application/ssml+xml
Path:ssml

<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="zh-CN">
    <voice name="zh-CN-XiaoshuangNeural">
        <prosody pitch="+0Hz" rate="+0%" volume="+0%">
    Hello world</prosody>
    </voice>
</speak>
```

**Comment by purkylin** [comment]
I use **raw-16khz-16bit-mono-pcm** format. If I use the default format(**audio-24khz-48kbitrate-mono-mp3**), it will work again.

**Comment by rany2** [comment]
Yeah this is the issue, Microsoft is cracking down on this library. You could only use functionality available in Edge by default.

**Comment by rany2** [comment]
@purkylin If you want a heads up, I think you should only use audio-24khz-48kbitrate-mono-mp3 or webm-24khz-16bit-mono-opus. Both are used by Edge so I think there is a good chance it will keep working for now..
