### ISSUE TITLE
example_err

### ISSUE THREAD

**Issue by rffanlab** [rany2/edge-tts#172]
https://github.com/rany2/edge-tts/blob/master/examples/streaming_with_subtitles.py

line 32 

file.write(submaker.generate_subs(TEXT))
should be

file.write(submaker.generate_subs(len(TEXT)))

**Comment by rany2** [comment]
It's actually not an error, this is for the newer version of edge_tts. See https://github.com/rany2/edge-tts/blob/5b7add93b9f64c27b5ed7138c30a1a4f25ba6a9d/examples/streaming_with_subtitles.py for how it should be currently done.
