### ISSUE TITLE
Subtitles don't like parentheses

### ISSUE THREAD

**Issue by Scoffins** [rany2/edge-tts#174]
New to GitHub so apologies if my terminology isn't correct.
I am using your latest update in "new-submaker" and mostly works great, but if the input text file contains a parentheses"(" or ")" right before the pattern character used for splitting, it stops outputting the subtitle right after that character.

E.g. if text file contains "Hello mate (friend). How are you?" it will stop right after (friend)

It also seems to happen if it's curly brackets {} aswel as parentheses.

Hope this makes sense.

**Comment by rany2** [comment]
It does make sense and I do know why this happens, the new-submaker code isn't great; I mostly got it from a PR I initially merged to master but it had too many issues that I just decided to not bother with it. I intend to redo it at some point.

**Comment by rany2** [comment]
Unfortunately I cannot fix it. Subtitles will now just contain the word that is being uttered.
