### ISSUE TITLE
Question: Will I be able to make multiple files at a same time?

### ISSUE THREAD

**Issue by jivangit** [rany2/edge-tts#177]
I love this project. I have been making audiobooks every hour of the day. I have been creating one at a time, but will i be able to create multiple instance at once? will it effect the generated mp3? what will be the issue, if there is any?

**Comment by rany2** [comment]
There shouldn't be any issues with doing that, at least I didn't face any issues running ~200 instances at once but that might have changed.

**Comment by songlen** [comment]
> 我喜欢这个项目。我每天每小时都在制作有声读物。我一次创建一个实例，但是我可以一次创建多个实例吗？会影响生成的mp3吗？如果有的话，会是什么问题？

亲，想跟您学习制作有声读物，嘿嘿

**Comment by nhan000** [comment]
I have a folder with multiple md files. How can I generate audio for that folder? Thanks!
