### ISSUE TITLE
Is there an alternative to edge-TTS?

### ISSUE THREAD

**Issue by APISeeker** [rany2/edge-tts#182]
Hello,
I like this a lot!
But to be REALLY safe, I would like to know that there are other alternatives just in case, what do you think are there alternatives like this and as good?
Thanks,

**Comment by rany2** [comment]
I don't know about as good (audio quality wise) and without any API keys. I was previously using gTTS which is pretty similar to edge_tts but doesn't sound really good.

**Comment by APISeeker** [comment]
It does not sound as good = the intonation etc?
This is hopefully going to stay then.

**Comment by rany2** [comment]
It's basically the same TTS you get from Google Translate.
