### ISSUE TITLE
Ampersand (&) is converted to HTML version (&amp;) in subtitles

### ISSUE THREAD

**Issue by Scoffins** [rany2/edge-tts#184]
When outputting subtitles, ampersands (&) in text input are converted to &amp; in the subtitles file.

This is a problem when using the subtitles file in things like FFMPEG.

**Comment by rany2** [comment]
Doesn't WebVTT require this? I think it's valid

**Comment by Scoffins** [comment]
I'm not sure about that but when I replace &amp; with & in the subtitle file it works perfectly. But I've only tested with FFMPEG so I don't know how it would respond to other encoders/players.

**Comment by rany2** [comment]
I'll be using a real subtitles library soon instead of my homegrown one which will support multiple subtitle formats. My WebVTT implementation is actually correct but unfortunately the support is a bit shoddy as it's not wildly used

**Comment by rany2** [comment]
Anyway it's not actually a bug, just caused by poor WebVTT support.
