### ISSUE TITLE
Different performance in diff network 

### ISSUE THREAD

**Issue by picturesque-software** [rany2/edge-tts#185]
I used clash system proxy in global and rule mode, and ran the example code.  It takes almost 10s to finish.
But if I ran the program without anonymous network, It takes 0.6s.
I want to know why and if I can use edgetts normally in clash env.

code:

`from datetime import datetime

import edge_tts
import asyncio

TEXT = ""
with open('text2voicetest.txt', 'rb') as f:
    data = f.read()
    TEXT = data.decode('utf-8')
print(TEXT)
voice = 'zh-CN-YunxiNeural'
output = 'text2voicetest.mp3'
rate = '-10%'
volume = '+0%'

async def my_function():
    time = datetime.now()
    print(time)
    tts = edge_tts.Communicate(text=TEXT, voice=voice, rate=rate, volume=volume)
    await tts.save(output)
    print(datetime.now())

if __name__ == '__main__':
    asyncio.run(my_function())`

**Comment by rany2** [comment]
The recent version might help with better performance on networks with high latency, if it doesn't then in all likelihood it's Microsoft throttling the service. I've observed that the Mb/s is very different depending on the network, so I assume there is a rate-limiting of sorts going on.
