### ISSUE TITLE
Problem for playing stream audio instantly using pydub

### ISSUE THREAD

**Issue by omicroh** [rany2/edge-tts#187]
Hello there,

I've been trying to implement fast audio streaming for 6 days now, but I just can't do it. Indeed, without the stream method, the save function of edge-tts takes about 1-2s to generate depending the text, which is too long.

In my code bellow, the audio is indeed played instantly, regardless of text size, but there are artefacts between chunks, like tiny spaces.

Do you know how to do audio streaming correctly please ? Thank you!

import asyncio
import edge_tts
import pyaudio
from io import BytesIO
from pydub import AudioSegment

TEXT = "Hello World!"
VOICE = "en-GB-SoniaNeural"

p = pyaudio.PyAudio()

async def stream_tts(text: str, voice: str) -> None:
    
    # We're assuming a certain format, channels, and rate
    # This will need to be dynamic based on the actual audio data from TTS
    stream = p.open(
        format=pyaudio.paInt16,
        channels=1,
        rate=26000,
        output=True
    )
    
    communicate = edge_tts.Communicate(text, voice)

    # Process and play audio chunks as they arrive
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            try:
                audio_segment = AudioSegment.from_file(BytesIO(chunk["data"]), format="mp3")
                
                # Write data to the stream directly without extra buffering
                stream.write(audio_segment.raw_data)
                
                # If this is the last chunk, break after playing
                if chunk.get('end', False):
                    break
            except Exception as e:
                print("Error processing audio chunk:", e)

    # Cleanup
    stream.stop_stream()
    stream.close()
    p.terminate()

if __name__ == "__main__":
    # Run the asyncio event loop
    asyncio.run(stream_tts(TEXT, VOICE))

@rany2

**Comment by rany2** [comment]
Maybe it is supposed to be like this? I'm sorry but I don't use pydub but the `p.open` line seems wrong.

```
stream = p.open(
    format=pyaudio.paInt16,
    channels=1,
    rate=48000,
    output=True
)
```

**Comment by Phouter0499** [comment]
So I got the audio streaming working. Here is the code:

```python
import asyncio
import edge_tts
from io import BytesIO
from pydub import AudioSegment
from pydub.playback import play

TEXT = "To Sherlock Holmes she is always the woman. I have seldom heard him mention her under any other name."
VOICE = "en-US-AndrewMultilingualNeural"

async def amain() -> None:
    communicate = edge_tts.Communicate(TEXT, VOICE)
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            try:
                buffer = BytesIO()
                buffer.write(chunk["data"])
                buffer.seek(0)
                audio_segment = AudioSegment.from_mp3(buffer)
                play(audio_segment)
                # If this is the last chunk, break after writing to buffer
                if chunk.get('end', False):
                    break
            except Exception as e:
                print("Error processing audio chunk:", e)   

if __name__ == "__main__":
    asyncio.run(amain())

```

**Comment by Phouter0499** [comment]
just tested with even bigger text (chapter 1 of sherlock holmes) but i notice that the stream is not instantaneous. maybe the online service processes all of the text first before they start streaming???

**Comment by rany2** [comment]
@Phouter0499 maybe, but I'm sending you the chunks as soon as I receive them; so whatever it is it's an issue on Microsoft's end

**Comment by FerLuisxd** [comment]
The audio breaks in @Phouter0499 example, is it expected? :/

**Comment by rany2** [comment]
@FerLuisxd If you're using large text please try the version in master (not pypi), recently #190 was fixed but I didn't make a release yet.

**Comment by FerLuisxd** [comment]
It is a short test, I managed to improve the speed a bit but it still does not feel right.
Here is the updated code

```python
import asyncio
import edge_tts
import pyaudio
from io import BytesIO
from pydub import AudioSegment

TEXT = "Hello World!"
VOICE = "en-US-AndrewMultilingualNeural"

async def amain() -> None:
    communicate = edge_tts.Communicate(TEXT, VOICE)
    p = pyaudio.PyAudio()
    stream = p.open(format=pyaudio.paInt16,
                    channels=1,
                    rate=24000,
                    output=True)
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            try:
                stream.write(AudioSegment.from_file(BytesIO(chunk["data"]), format="mp3").raw_data)

                # If this is the last chunk, break after writing to buffer
                if chunk.get('end', False):
                    break
            except Exception as e:
                print("Error processing audio chunk:", e)

    if stream:
        stream.stop_stream()
        stream.close()
    p.terminate()

if __name__ == "__main__":
    asyncio.run(amain())
```

Here is @Phouter0499 version:

```python
import asyncio
import edge_tts
from io import BytesIO
from pydub import AudioSegment
from pydub.playback import play

TEXT = "Hello World!"
VOICE = "en-US-AndrewMultilingualNeural"

async def amain() -> None:
    communicate = edge_tts.Communicate(TEXT, VOICE)
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            try:
                buffer = BytesIO()
                buffer.write(chunk["data"])
                buffer.seek(0)
                audio_segment = AudioSegment.from_mp3(buffer)
                play(audio_segment)
                # If this is the last chunk, break after writing to buffer
                if chunk.get('end', False):
                    break
            except Exception as e:
                print("Error processing audio chunk:", e)   

if __name__ == "__main__":
    asyncio.run(amain())
``` 

If you test both codes it still feels like it is reading it letter by letter, I'm wondering if there is a way so it can read it faster? 🤔

**Comment by FerLuisxd** [comment]
I wonder if @omicroh managed to find a solution as well

**Comment by rany2** [comment]
FYI there is no such thing as:

```
                # If this is the last chunk, break after writing to buffer
                if chunk.get('end', False):
                    break
```

I'm not sure where they got that from, I don't think you need it.

**Comment by Phouter0499** [comment]
> The audio breaks in @Phouter0499 example, is it expected? :/

What os are you using?
I tried this code again on my linux machine and looks like the code doesn't work and the audio seems like it was sped up or something.
When I tried this on my windows laptop. It worked just fine.

**Comment by Phouter0499** [comment]
> I'm using windows, and using the latest 6.1.11 version Python is 3.11.3
> 
> Thanks for your test! What you mean by "it worked just fine", I feel like what @Phouter0499 wanted is to be similar to the output .mp3 file but without having to wait for the whole file. In my computer it says it letter by letter and with noticiable spaces between them, I'd say around 0.3% speed of the .mp3 file What about when you tried it?

sorry for the late response. 
I meant that when I made my example, it was able to successfully play the sounds returned from the communicate.stream method very smoothly without breakage or weird whatever. However, when I tested this example on my windows just now, it doesn't work anymore. Frankly I have no idea what is happening. I am going to continue working on this....

**Comment by FerLuisxd** [comment]
@Phouter0499 , I saw an error with your code and the reason of my it may be producing sounds faster, and that is because of the rate you put originally, it is not 26000 but 24000, if you increase the number even further it may sound faster but higher pitched

**Comment by Phouter0499** [comment]
So this time I think I made it work but there is a limitation. So I tested the below code with the first of the sherlock holmes series. However, there does seem to be a slight breakage after every 20 chunks BUT the streaming was instant...please try this one and tell me if it works. You also have to install just_playback and download some book or long text file.  
```python
import edge_tts
import just_playback
import os
import time

with open("pg1661.txt", "r", encoding="utf-8") as f:
    TEXT = f.read()
VOICE = "en-US-AndrewMultilingualNeural"

def main() -> None:
    communicate = edge_tts.Communicate(TEXT, VOICE)
    group_chunk_size = 20
    n_chunk_written = 0
    playback = just_playback.Playback()
    for chunk in communicate.stream_sync():
        if chunk["type"] == "audio":
            try:
                # this is last chunk (empty)
                if chunk['data'] == b'':
                    continue
                with open("temp.mp3", "ab") as f:
                    f.write(chunk['data'])
                    n_chunk_written += 1
                if n_chunk_written == group_chunk_size:
                    playback.load_file('temp.mp3')
                    playback.play()
                    while playback.active:
                        time.sleep(0.001)
                    n_chunk_written = 0
                    os.remove("temp.mp3")                    
            except Exception as e:
                print("Error processing audio chunk:", e)

if __name__ == "__main__":
    if os.path.exists("temp.mp3"):
        os.remove("temp.mp3")
    main()
```

**Comment by FerLuisxd** [comment]
Wow this is much better! Tried it with a random gpt response I had (around 300 words). It played correctly for a few seconds (around 5) but then I got:
```
Error processing audio chunk: [WinError 32] The process cannot access the file because it is being used by another process: 'temp.mp3'
Error processing audio chunk: [Errno 13] Permission denied: 'temp.mp3'
````
It also seems to always fail the same time everytime I run it 🤔.
Wonder if it is necessary to save it into the file and not play it on the go...

**Comment by rany2** [comment]
@FerLuisxd I took at the just_playback code, I think you should do this (sorry untested and on mobile atm):

```python3
import edge_tts
import just_playback
import os
import time

with open("pg1661.txt", "r", encoding="utf-8") as f:
    TEXT = f.read()
VOICE = "en-US-AndrewMultilingualNeural"

def main() -> None:
    communicate = edge_tts.Communicate(TEXT, VOICE)
    group_chunk_size = 100
    n_chunk_written = 0
    for chunk in communicate.stream_sync():
        if chunk["type"] == "audio":
            try:
                # this is last chunk (empty)
                if chunk['data'] == b'':
                    continue
                with open("temp.mp3", "ab") as f:
                    f.write(chunk['data'])
                    n_chunk_written += 1
                if n_chunk_written == group_chunk_size:
                    playback = just_playback.Playback('temp.mp3')
                    playback.play()
                    while playback.active:
                        time.sleep(0.001)
                    del playback
                    n_chunk_written = 0
                    os.remove("temp.mp3")                    
            except Exception as e:
                print("Error processing audio chunk:", e)

if __name__ == "__main__":
    if os.path.exists("temp.mp3"):
        os.remove("temp.mp3")
    main()
```

**Comment by Phouter0499** [comment]
> @FerLuisxd I took a look at the just_playback code, I think you should do this (sorry untested and on mobile atm):

playback.__del__() causes "Segmentation fault (core dumped)" error.

**Comment by rany2** [comment]
It's probably a bug with that library, it's not closing the file once it's done with it.

**Comment by FerLuisxd** [comment]
Sadly that did not fix the issue, it still fails at the exact same time :/ 
```
$ python github.py
Segmentation fault
```

**Comment by FerLuisxd** [comment]
Hey @Phouter0499 ! I think Claude Sonnet helped me here! Please try this with your own text and tell me how it goes!
```python
import edge_tts
import os
import pyaudio
from io import BytesIO
from pydub import AudioSegment

TEXT = 'Hello World! How are you guys doing? I hope great , cause I am having fun and honestly it has been a blast'
VOICE = "en-US-AndrewMultilingualNeural"

def main() -> None:
    communicate = edge_tts.Communicate(TEXT, VOICE)
    group_chunk_size = 50
    n_chunk_written = 0
    chunks = []

    p = pyaudio.PyAudio()
    stream = p.open(format=pyaudio.paInt16,
                    channels=1,
                    rate=24000,
                    output=True)

    for chunk in communicate.stream_sync():
        if chunk["type"] == "audio":
            try:
                # Ignore the last chunk (empty)
                if chunk['data'] == b'':
                    continue

                chunks.append(chunk["data"])
                n_chunk_written += 1

                if n_chunk_written == group_chunk_size:
                    combined_mp3 = b''.join(chunks)
                    audio_segment = AudioSegment.from_file(BytesIO(combined_mp3), format="mp3")
                    raw_data = audio_segment.raw_data
                    stream.write(raw_data)
                    n_chunk_written = 0
                    chunks = []

            except Exception as e:
                print("Error processing audio chunk:", e)

    # Write any remaining data
    if chunks:
        combined_mp3 = b''.join(chunks)
        audio_segment = AudioSegment.from_file(BytesIO(combined_mp3), format="mp3")
        raw_data = audio_segment.raw_data
        stream.write(raw_data)

    stream.stop_stream()
    stream.close()
    p.terminate()

if __name__ == "__main__":
    main()
```

**Comment by Phouter0499** [comment]
> Hey @Phouter0499 ! I think Claude Sonnet helped me here! Please try this with your own text and tell me how it goes! Also tried it with longer TEXT from before and it worked! It didn't crash this time!

works on my linux machine. I notice the "ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred" errors but this isn't too bad.

**Comment by FerLuisxd** [comment]
Maybe try to play around with the group_chunk_size?

**Comment by Phouter0499** [comment]
> Maybe try to play around with the group_chunk_size?
100 is good for me but maybe tomorrow I will try some concurrency to get rid of the usage of group_chunk_size.

**Comment by FerLuisxd** [comment]
I just asked and it seems to be a CPU bottleneck related? I don't see that error at all on my PC, @rany2 @omicroh  do you think you could test my code and let us know as well? 🙏

**Comment by laycookie** [comment]
Hi. Played a bit around with it, as I have encountered a similar issue. The problem is not the performance, the problem is in loose of data when converting from wav to mp3 and back mp3 to wav. 
I'm a bit tired for getting in to details, but long story short you need neighboring mp3 chunks to be able to properly convert a chunk in to its wav version, otherwise the data at the edges will get lost, resulting in a choppy sound.

Here is a simulation of how the corruption sounds, which is 1 to 1 what I'm getting from just playing the chunks directly.

[OGSample.mp3](https://github.com/user-attachments/files/22184697/OGSample.mp3)

[coruptedSample.mp3](https://github.com/user-attachments/files/22184701/coruptedSample.mp3)
