### ISSUE TITLE
GPU voice render

### ISSUE THREAD

**Issue by Ranzie12** [rany2/edge-tts#191]
Is there a possibility I can run the Edge TTS code on a CUDA GPU to render the voice at a faster rate? also how can i know what are the list of voices in this package

**Comment by rany2** [comment]
No, it uses the online service only. You could use `edge-tts -l` for cli or something similar to this code snippet from library: https://github.com/rany2/edge-tts/blob/5b7add93b9f64c27b5ed7138c30a1a4f25ba6a9d/src/edge_tts/util.py#L15
