### ISSUE TITLE
Where can I find the ORIGINAL edge technology repo? And all the voices available?

### ISSUE THREAD

**Issue by APISeeker** [rany2/edge-tts#192]
Hello
I am using a tech related to edge, and it has a certain number of voices, but I am not sure I have the whole list, where can i find all the info related to the original project? And find ALL the actual voices actually available and offered etc?

Thanks

**Comment by rany2** [comment]
https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4

**Comment by APISeeker** [comment]
Thanks a lot!
But where is the link to the actual ORIGINAL product please? @rany2 .?
I tried : https://[speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/](https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/)
or speech.platform.bing.com ..

They did not work

**Comment by rany2** [comment]
The original product is the Edge Browser's Read Aloud feature. This is using the same API.

**Comment by APISeeker** [comment]
So that github repo I found earlier with not many stars made for reading the tabs of a browser? But I thought that itself WAS MADE on top of another product.
My question is how did you find that link please? (the one you gave me) 
I mean I am trying to get into "speech.platform.bing" or something. The real sources of the thing. Oh weell
