### ISSUE TITLE
Make it possible to use edge-tts without async

### ISSUE THREAD

**Issue by xiaobili** [rany2/edge-tts#194]
The stream method in the communicate object seems to only have asynchronous generators.

there is a Scenes，that i want to use flask to send byte data to client，but the flask doesn't support async generator

**Comment by FujiwaraChoki** [comment]
+1

**Comment by rany2** [comment]
This feature was added by @lzieniew in 6.1.11.

**Comment by FujiwaraChoki** [comment]
lets gooo
