### ISSUE TITLE
safety

### ISSUE THREAD

**Issue by yiwei0730** [rany2/edge-tts#199]
Does using this model without a key run the risk of edge TTS? Want to know if there is any safety or future harm part

**Comment by rany2** [comment]
I don't understand what you mean by "stealing edge TTS."

**Comment by yiwei0730** [comment]
sorry my bad, i use the google translate and not check out. i'm just asking the risk
I just want to know is there have any security or risks using edge TTS and code, such as: access being interrupted or other possible problems

**Comment by rany2** [comment]
There is always a chance Microsoft would block this, but seeing this has worked for a couple of years now I don't think Microsoft cares about this much.
