### ISSUE TITLE
Adding a simple example of how to use the application in Python

### ISSUE THREAD

**Issue by Vuizur** [rany2/edge-tts#20]
First of all, thanks for creating this library, the results are amazing. 

I thought it would be cool to have an example for the usage of the library in Python to output an mp3, because the current one in the examples folder was not applicable to my situation and I wasted too much time getting it to work.

So what I ended up with was:

```python
def read_story(story: str, voice: str, filename: str):
    
    with open(f"{filename}.txt", "w", encoding="utf-8") as f:
        f.write(story)
    command = f'edge-tts --file "{filename}.txt" --write-media "{filename}.mp3" --voice {voice}'
    res = subprocess.check_output(command, shell=True)
    print(res)
```

**Comment by rany2** [comment]
An example does already exist: https://github.com/rany2/edge-tts/blob/master/examples/input_example.py

and for a more advanced one you could see https://github.com/rany2/edge-srt-to-speech/blob/master/src/edge_srt_to_speech/__main__.py

If you want a more popular real world project: https://github.com/hasscc/hass-edge-tts

**Comment by Vuizur** [comment]
I tried using the first example, but I think I couldn't figure out how to save it to a file. (It is probably trivial, but I have no experience with Python async.)

**Comment by rany2** [comment]
```
import asyncio
import edge_tts

async def main():
    communicate = edge_tts.Communicate()
    text = "This is what will be said by the TTS."
    file = "output.mp3"
    with open(file, "wb") as file:
        async for i in communicate.run(text):
            if i[2] is not None:
                file.write(i[2])

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

**Comment by rany2** [comment]
i[0] = offset
i[1] = text
i[2] = audio data

You need to set boundary_type to 1 if you want the offset and text metadata. It basically allows you to highlight which word will be said by the TTS at what time.

**Comment by Vuizur** [comment]
Thank you very much for the help!

**Comment by rany2** [comment]
I've listed all the examples here: https://github.com/rany2/edge-tts#python-module. Thanks!

**Comment by lonngxiang** [comment]
run error：
![image](https://github.com/rany2/edge-tts/assets/40717349/ac9b0d5f-e837-4c08-84ca-c80cf6210c01)
