### ISSUE TITLE
Trying to understand EDGE FULLY - Where is its SOURCE?

### ISSUE THREAD

**Issue by GithubStable** [rany2/edge-tts#208]
Hello,
The only way I have heard about EDGE is through this repositories,
But I believe EDGE exists outisde this right? I tried to search for ITS SOURCES, and I was able to find is something about a Text to Speech for html pages?
And also, something about voices being availble in AZURE? And the service being maybe paid?

I would like someone to explain to me how to set up EDGE, without using this repository, I just want to try to understand it better, and have better control of what's going on? Can someone give me some directions on where to start?

**Comment by GithubStable** [comment]
Is this code written by you or provied by microsoft? Thanks

**Comment by rany2** [comment]
By me.

**Comment by GithubStable** [comment]
Ok one last question: if I were to try to replicate it (without copying your code) where would be the starting point, Microsoft has intructions somewhere? That's what I meant first when I wrote "original"
Thanks^^ That was my last question.

**Comment by rany2** [comment]
They definitely do not have instructions. It's the result of checking the network traffic from edge browser.

**Comment by GithubStable** [comment]
> They definitely do not have instructions. It's the result of checking the network traffic from edge browser.

Wow!
You have no idea how useful your work is by the way. I thank you sincerely. Especially that it is used in another repo that is dear to me.

**Comment by GithubStable** [comment]
@rany2 , I am curious though (Sorry I said the other was my last question, I have another one). Do you know "rvc-tts-webui"? It uses Edge! 
And when using it, it allows you to use another voice model, BUT it is "tailored" to be close to the voices from edge (Ryan EN etc)
My question is do you know how that works? and Do you know if it possible to do the same but other technologies, the one that let you change the emotions (and tone etc), there is another TTS "Style-Bert-VITS2" tech that let you do that but I have no idea how.. associate it.. with EDGE. I Hope you could be of help if you checked how "rvc-tts-webui" worked.

??
What do you think?
Is that doable?

**Comment by GithubStable** [comment]
Please?

**Comment by rany2** [comment]
> the one that let you change the emotions (and tone etc), there is another TTS "Style-Bert-VITS2" tech that let you do that but I have no idea how.. associate it.. with EDGE. I Hope you could be of help if you checked how "rvc-tts-webui" worked.

It worked because at the time edge-tts had support for this but Microsoft has since filtered out anything that uses "custom SSML." Only features the Edge Browser supports could be used.

**Comment by rany2** [comment]
See this https://github.com/rany2/edge-tts/issues/58

**Comment by GithubStable** [comment]
> > the one that let you change the emotions (and tone etc), there is another TTS "Style-Bert-VITS2" tech that let you do that but I have no idea how.. associate it.. with EDGE. I Hope you could be of help if you checked how "rvc-tts-webui" worked.
> 
> It worked because at the time edge-tts had support for this but Microsoft has since filtered out anything that uses "custom SSML." Only features the Edge Browser supports could be used.

Oh really? When did it stop?  But I am still able to "change" the "voice form" generated with rvc-tts-webui" so I am surprised, while relying on edge. You should check their code and see what's up, maybe you will find something interested (the repo is achived but still available)
Do you know other text to speech as powerful and GOOD as edge? (not paid ones like Eleven.. ofc)

**Comment by GithubStable** [comment]
well I am not sure it is SSML, the thing you mentioend, but yes I can make voices related to edge (with my own .pth), are we sure we are talking about the same thing? Because I don't know a lot of about SSML and I don't know about the code related to edge on that repo

**Comment by rany2** [comment]
Wait, so basically I think I figured out how that works; it's not custom SSML. Basically, it seems like it generates the audio as normal with edge-tts and then using some kind of RVC library that changes the voice to something else; I think that's how it works.

**Comment by GithubStable** [comment]
At least show me where is the part where you think there is a use of a library that changes the voice. Maybe I can learn myself to do what I am seeking (I tried to ask on the style repo but did not get participation yet)
seriously do you think I can do it with other libraries,I would LOVE to change the emotions. Please tell me

**Comment by rany2** [comment]
This is obviously beyond the scope of this project, but someone could always create a new project that uses edge-tts and some library to do the same thing. I might research it a bit more to see how complicated it is to do this myself, seems interesting.

**Comment by GithubStable** [comment]
Thank you, will  you inform me of your advancements please?

**Comment by Erquint** [comment]
I am very invested into this discussion and sad to see SSML go.  
I assume when you say "custom SSML" — you refer to any SSML the user enters.  
However, I distinctly recall 3rd-party document somewhere claiming that Edge TTS supports SSML, but only three of its tags: breakm, prosody, and maybe phoneme, tough to recall specifics.  
Probably outdated…

**Comment by rany2** [comment]
@Erquint This is true, but it only allows a single voice and prosody element. You could configure the parameters to it via edge-tts' options.

edge-tts allows you set voice, rate, pitch and volume.

**Comment by Erquint** [comment]
Much like OP I am interested in borrowing the reverse-engineered insight for this undocumented M$ APi for Edge TTS rather than necessarily using your code as a solution. I may later down the line, but for now I'd appreciate you elaborating on how exactly the API does and doesn't accept those SSML directives. Are you saying it requires wrapping the entire text with it? Or only one of each tags anywhere in the string? Or are these passed as a separate parameter of the request? What are the specific limitations?
