### ISSUE TITLE
can I communicate directly to edge-tts's api?

### ISSUE THREAD

**Issue by jiangyin14** [rany2/edge-tts#209]

**Comment by rany2** [comment]
What do you mean?

**Comment by jiangyin14** [comment]
i mean, i want to use the edge-tts's api but i can't figure out how your project works(bcuz i don't master Rust), but i saw a package in NuGet, still thank you for answering me
sry but my english is bad🤣

**Comment by rany2** [comment]
You could take a look at https://github.com/rany2/edge-tts?tab=readme-ov-file#python-module
