### ISSUE TITLE
Limits on the TRUSTED_CLIENT_TOKEN 

### ISSUE THREAD

**Issue by cmalzatet** [rany2/edge-tts#21]
Hi! 
I would like to ask if there is a limit to the TRUSTED_CLIENT_TOKEN used in the library, like number of synthesis or somethign like that.

Thank you for your help.

**Comment by rany2** [comment]
`TRUSTED_CLIENT_TOKEN` is the same as the one used in the Microsoft Edge browser, so there shouldn't be any noticeable limits if you're using it normally. The only limit with the API I was able to find is that it starts returning 429 if you flood it with 500 connections in parallel, but if you stay moderate about your # of connections and have some cooldown time then it would be fine. 

Any 429 block is temporary and goes away in 5 minutes.

**Comment by rany2** [comment]
Also you can't use any of the Azure Cognitive Services features anymore (unless they are also accessible in Microsoft Edge), so for example expression/emotion, background audio, other MS SSML additions are not possible. They had blocked them a while ago.

**Comment by NimayDono** [comment]
> Hi! I would like to ask if there is a limit to the TRUSTED_CLIENT_TOKEN used in the library, like number of synthesis or somethign like that.
> 
> Thank you for your help.

Tested on 2495 consecutive short requests. One error on 416. Reliable enough.

**Comment by jinfagang** [comment]
@rany2 what could happen if I run it synethsis 2 days with every sentence 1s break?

**Comment by rany2** [comment]
@lucasjinreal I don't know, did you end up doing this?
