### ISSUE TITLE
Microsoft recently released new sound model...

### ISSUE THREAD

**Issue by szj2ys** [rany2/edge-tts#211]
Microsoft recently released new sound model, it seems that this project does not support, can you add it? Thank you!

**Comment by rany2** [comment]
You mean speech to text?

**Comment by yang827** [comment]
I think he is referring to "Text to Speech." It is an AI speech feature that converts text into lifelike speech.
[https://azure.microsoft.com/en-us/products/ai-services/text-to-speech/#get-started](url)

**Comment by rany2** [comment]
I can't add support to features that aren't in the Edge browser. I'll reopen this if this is functionality found in Edge.
