### ISSUE TITLE
any plan update for new voices

### ISSUE THREAD

**Issue by GH3a** [rany2/edge-tts#212]
en-US-AvaMultilingualNeural
en-US-AndrewMultilingualNeural
en-US-EmmaMultilingualNeural
en-US-BrianMultilingualNeural
De-DE-FlorianMultilingualNeural
De-DE-SeraphinaMultilingualNeural
Fr-FR-RemyMultilingualNeural
Fr-FR-VivienneMultilingualNeural
zh-CN-XiaoxiaoMultiligualNeural

**Comment by rany2** [comment]
If edge tts doesn't return audio then it's not supported

**Comment by rany2** [comment]
Please understand that edge-tts only supports voices that are supported by Edge Browser, anything else gets filtered out by Microsoft. Edge Browser has a proxy to Azure AI services that sanitizes the inputs.
