### ISSUE TITLE
能整合到网页里吗？任何平台的任何浏览器都能用吗？

### ISSUE THREAD

**Issue by niubility000** [rany2/edge-tts#213]
看到个这个https://wiggins.blog.csdn.net/article/details/135631137?spm=1001.2101.3001.6650.1&utm_medium=distribute.wap_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7EPayColumn-1-135631137-blog-134303150.237%5Ev3%5Ewap_relevant_t0_download&depth_1-utm_source=distribute.wap_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7EPayColumn-1-135631137-blog-134303150.237%5Ev3%5Ewap_relevant_t0_download，可惜要花钱才能看到。怎么整合到网页里呢？用java script.

**Comment by rany2** [comment]
Unfortunately, you will need some kind of Flask application (to act as some proxy) to make this work. It's a real struggle because if you make the call from a webpage; the "Origin" header cannot be spoofed and your request will fail.

**Comment by liuyanfeng-githug** [comment]
我将这个服务整合到网页当中供大家使用  https://dub.lyfdev.com
