### ISSUE TITLE
support new OpenAI  tts  

### ISSUE THREAD

**Issue by fastfading** [rany2/edge-tts#214]
https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/language-support?tabs=tts

en-US-AlloyMultilingualNeural4（男）
en-US-EchoMultilingualNeural4（男）
en-US-FableMultilingualNeural4（中性）
en-US-OnyxMultilingualNeural4（男）
en-US-NovaMultilingualNeural4（女）
en-US-ShimmerMultilingualNeural4（女）
en-US-AlloyMultilingualNeuralHD4（男）
en-US-EchoMultilingualNeuralHD4（男）
en-US-FableMultilingualNeuralHD4（中性）
en-US-OnyxMultilingualNeuralHD4（男）
en-US-NovaMultilingualNeuralHD4（女）
en-US-ShimmerMultilingualNeuralHD4（女）

4 Azure AI 语音中的 OpenAI 文本转语音声音为公开预览版，仅在美国中北部 (northcentralus) 和瑞典中部 (swedencentral) 提供。

**Comment by rany2** [comment]
Unfortunately, this program could only work with voices that are supported by the Edge Browser. I do not use the Azure AI services directly, but only through the proxy used by the Edge Browser.
