### ISSUE TITLE
Add "-" as a valid parameter for input/output parameters

### ISSUE THREAD

**Issue by j824h** [rany2/edge-tts#216]
Reading from the standard input like many other command line tools could be helpful.

Especially, with `edge-playback` it would allow a streamlined workflow completely free of intermediate files.

**Comment by rany2** [comment]
`edge-tts` already supports this, it's only `edge-playback` that has this limitation. What you could do is the following:

```
<some program> | edge-tts --file /dev/stdin 2>/dev/null | mpv -
```

**Comment by j824h** [comment]
That makes sense. I see `/dev/stdin` is a file of course.

Still you wouldn't plan to alias with `-` as `mpv` does?

**Comment by rany2** [comment]
`/dev/stdin` is actually an alias for stdin, it's handled in edge-tts so it works even if that file doesn't exist (i.e., this works on Windows too)

**Comment by j824h** [comment]
I see `/dev/stdin` is actually an alias that works even for Windows.
I suppose you want to keep it as the only and correct way?

**Comment by rany2** [comment]
To be honest, I think it's quite confusing. I'll update it and add `-` as a supported parameter. You would never guess this if you didn't check the code.
