### ISSUE TITLE
Is there quota for the tts service?

### ISSUE THREAD

**Issue by boveyking** [rany2/edge-tts#219]
This project is awesome. Seems free without api or account required. I would like to know if there is quota imposed on request rate, for example, how many chars we can convert using microsoft service? If yes,  how to pay the fee to use the service ? thanks.

**Comment by rany2** [comment]
The exact quota is unknown but it seems like it's generous enough that you're unlikely to hit it. For the paid service, you should look into Azure Cognitive Services; it's not expensive.
