### ISSUE TITLE
Multilingual voice will change language unintentionally

### ISSUE THREAD

**Issue by Xascoria** [rany2/edge-tts#225]
For example:

`Microsoft Server Speech Text to Speech Voice (en-US, AndrewNeural)`

Will switch to French automatically when reading the sentence `Fines plus a charge?`, even when the specified voice is English, as can be seen above, instead of `Microsoft Server Speech Text to Speech Voice (en-US, AndrewMultilingualNeural)`

Is there any way to prevent this or to force the language to be English?

**Comment by rany2** [comment]
Unfortunately this is a server-side issue. There's nothing I could do about it
