### ISSUE TITLE
Few words are dropped when sending many requests in parallel

### ISSUE THREAD

**Issue by didi666** [rany2/edge-tts#230]
I use asynchronous concurrent speech generation. Often you get incomplete speech. Every voice. You end up missing dozens or hundreds of words.

**Comment by didi666** [comment]
I use 6.1.12, including the previous will also be lost. Now 6.1.12 is the same.I'm using Chinese

**Comment by rany2** [comment]
It seems like a server issue, I'm not sure if we could detect when the server is about to drop words or not.

**Comment by didi666** [comment]
Single generated voice is not found missing, I use multithreading plus asynchronous, 5 threads, 10 asynchronous each thread. An asynchronous 1600 word. Each asynchronously generated piece of audio has a certain chance of losing about 100 words of content.

**Comment by rany2** [comment]
I can't find anything I could do to fix this. The responses I'm getting back when this issue occurs is normal.
