### ISSUE TITLE
Save as wav?

### ISSUE THREAD

**Issue by fwmd7** [rany2/edge-tts#232]
Is there any way to save the audio in wav format? Does the endpoint support returning the audio in wav format?

**Comment by rany2** [comment]
The endpoint only supports mp3 and webm, but webm isn't used by the Edge Browser so I don't want to rely on it. At any rate, the audio quality in webm format (it uses opus but at a very low bitrate) is inferior and you could notice some crackling so I wouldn't recommend it.

I recommend you use something like ffmpeg to convert to WAV if it's a requirement. There might be a Python library that is better integration/suitable for that task as well, so you will need to do some research.
