### ISSUE TITLE
Connection timeout to host wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=79d29bf64dbf4212a779eaef6dd2f594

### ISSUE THREAD

**Issue by xddcode** [rany2/edge-tts#235]
Multiple tasks are called asynchronously at the same time, and the previous task throws an error：

Connection timeout to host wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=79d29bf64dbf4212a779eaef6dd2f594

**Comment by rany2** [comment]
Reduce the # of tasks started. Microsoft randomly drops audio segments or blocks you at the network level if you're sending too many requests, especially concurrently.

**Comment by HYJ-creator** [comment]
Connection timeout to host wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken 
I meet the same problem, but i just rum 'basic_generation.py'
