### ISSUE TITLE
Example to play audio chunks via pydub

### ISSUE THREAD

**Issue by criminact** [rany2/edge-tts#236]
Could you please provide an example to play the audio chunks being streamed using pydub or any other python lib

**Comment by rany2** [comment]
Unfortunately there is no such example, but you should be able to convert the mp3 chunks to wav and then play them back.

**Comment by rany2** [comment]
Note you cannot modify the audio format, it only supports webm and mp3 but the webm output quality is much worse (opus at a very lower bitrate). Also because the official client doesn't seem to ever use webm, there is no support to request it from the library.

**Comment by riddlegit** [comment]
``` python
import asyncio
import edge_tts
import pygame
from io import BytesIO

async def main():
    pygame.mixer.init()

    tts = edge_tts.Communicate("你好，世界！", "zh-CN-XiaoxiaoNeural")

    mp3_data = bytearray()
    async for chunk in tts.stream():
        if chunk["type"] == "audio":
            mp3_data.extend(chunk["data"])

    mp3_stream = BytesIO(mp3_data)
    pygame.mixer.music.load(mp3_stream)
    
    pygame.mixer.music.play()
    while pygame.mixer.music.get_busy():
        await asyncio.sleep(0.1)
asyncio.run(main())
```

**Comment by criminact** [comment]
Thanks, Check this as well - https://github.com/rany2/edge-tts/issues/187#issuecomment-2126006007
