### ISSUE TITLE
[Question] speech.platform.bing.com service down

### ISSUE THREAD

**Issue by ansonhorse** [rany2/edge-tts#240]
It seems that the `speech.platform.bing.com` is down.

`edge-playback --text "Hello, world"` result:

```
...
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host speech.platform.bing.com:443 ssl:<ssl.SSLContext object at 0x103cad940> [nodename nor servname provided, or not known]
```

Direct access [https://speech.platform.bing.com/](https://speech.platform.bing.com/) result:
```
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>...=
```

I will continue to pay attention to the status of this service in the next period of time.

**Comment by ansonhorse** [comment]
This chrome extension [MS Edge TTS (Text to Speech)](https://chromewebstore.google.com/detail/ms-edge-tts-text-to-speec/oajalfneblkfiejoadecnmodfpnaeblh) still works, it uses WebSocket to commucate with `wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1`

**Comment by rany2** [comment]
No difference, I'm using the same endpoint.

https://github.com/rany2/edge-tts/blob/dfd4cab849a988d9587684cf3f9f9536c92b8f4d/src/edge_tts/constants.py#L6-L10

**Comment by rany2** [comment]
Anyway I don't have this issue, maybe it was an intermittent issue?

**Comment by ansonhorse** [comment]
I have confirmed that it is my network problem. Sorry to bother

**Comment by rany2** [comment]
No worries, thanks for confirming :)

**Comment by xiaofengsoft** [comment]
> I have confirmed that it is my network problem. Sorry to bother

How did you fix that problem , I have just met this question.
![image](https://github.com/user-attachments/assets/ec1bd749-7694-4ecf-9a46-7a2aa1503325)
