### ISSUE TITLE
Take standard input

### ISSUE THREAD

**Issue by winstonma** [rany2/edge-tts#242]
I would like use [percollate](https://github.com/danburzo/percollate) to extract the web page to text and feed the edge-tts through standard input. The following would be a demo of the desired format:

```bash
# "Hello World" would be read out
echo "Hello World" | edge-playback -t
```

Thanks for your time

**Comment by WillJDunn** [comment]
If you have a command line program that writes to standard out, you should be able to use command substitution like this:
```bash
edge-tts --text $(echo 'Hello World')
```

**Comment by rany2** [comment]
You could use `-f /dev/stdin` (works on Windows as well).

**Comment by winstonma** [comment]
@rany2 Thanks it works

```bash
# Doesn't work for me
$ edge-tts --text $(echo "Hello World")
usage: edge-tts [-h] [-t TEXT] [-f FILE] [-v VOICE] [-l] [--rate RATE] [--volume VOLUME] [--pitch PITCH] [--words-in-cue WORDS_IN_CUE]
                [--write-media WRITE_MEDIA] [--write-subtitles WRITE_SUBTITLES] [--proxy PROXY]
edge-tts: error: unrecognized arguments: World

# Working solution
$  echo "Hello World" | edge-playback -f /dev/stdin
```
