### ISSUE TITLE
[Suggestion] edge-translate

### ISSUE THREAD

**Issue by Bardo-Konrad** [rany2/edge-tts#246]
Now you figured out how to do edge-tts via python, can you also make edge-translate work?

**Comment by rany2** [comment]
I'm uninterested.

**Comment by Bardo-Konrad** [comment]
> I'm uninterested.

That was rude. Can you elaborate why it's too challenging for you?

**Comment by rany2** [comment]
There are lots of free high quality translation APIs available. What is the point?

**Comment by Bardo-Konrad** [comment]
> There are lots of free high quality translation APIs available. What is the point?

Tell me those that are free without rate limit.

**Comment by rany2** [comment]
I just use Google Translate's endpoint:

```py3
import json, requests, urllib.parse

def translate(text: str, from_lang: str = "auto", to_lang: str = "en"):
        url = f"https://translate.google.com/translate_a/single?client=gtx&sl={urllib.parse.quote_plus(from_lang)}&tl={urllib.parse.quote_plus(to_lang)}&dt=t&q={urllib.parse.quote_plus(text)}"
        response = requests.get(url)
        data = json.loads(response.text)
        new_data = ""
        for iter_data in data[0]:
            new_data += f"{iter_data[0]}"
        return new_data
```
