### ISSUE TITLE
Make the Module and CLI similar to gTTS

### ISSUE THREAD

**Issue by rifkyashari** [rany2/edge-tts#25]

**Comment by rany2** [comment]
I'll have a look at gTTS and maybe copy their interface. We'll see

**Comment by rifkyashari** [comment]
Thank, you're making good stuff here.

**Comment by rifkyashari** [comment]
and also how do change the language and the pitch?

**Comment by rany2** [comment]
https://github.com/rany2/edge-tts#changing-pitch-rate-volume-etc

**Comment by rany2** [comment]
Done as of 6.0.x
