### ISSUE TITLE
ConnectionTimeoutError:

### ISSUE THREAD

**Issue by HYJ-creator** [rany2/edge-tts#251]
Connection timeout to host wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId= ....

when i run "edge-tts/examples/basic_generation.py", i got this error

**Comment by rany2** [comment]
It seems like it's a connection issue. I don't have this issue.

**Comment by kevindevm** [comment]
same, started 3 days ago

**Comment by xshuai1006** [comment]
I also encounter this problem now.

**Comment by xshuai1006** [comment]
> I also encounter this problem now.
I upgrade edge-tts to the latest version 6.12 and try again, the issue disappears. May be it's just temporary connection issue.

**Comment by xshuai1006** [comment]
> > I also encounter this problem now.
> > I upgrade edge-tts to the latest version 6.12 and try again, the issue disappears. May be it's just temporary connection issue.

6.1.12

**Comment by einsqing** [comment]
Is there a solution to this?

**Comment by raymerjacque** [comment]
im having thiis problem, any solutions ?

**Comment by rany2** [comment]
It's just a connection issue. It could also happen because Bing is blocked, in that case it might be worth trying a proxy.

**Comment by malikhamza244** [comment]
Same issue can anyone found solution?
