### ISSUE TITLE
nonRIFF format

### ISSUE THREAD

**Issue by rpatapa** [rany2/edge-tts#253]
Apparently, the audio file generated using the **--write-media** generates a non-RIFF format based file. Hence, it is getting difficult in some situations to play that file immediately after generation. 

It is possible that edge-tts generates the audio in standard RIFF format supported file?

**Comment by rany2** [comment]
It's not possible unfortunately. In the past, we also had support for webm but the quality was very poor due to low sample rate. MP3 is the only other supported output format by the API.
