### ISSUE TITLE
How many tones can be supported?

### ISSUE THREAD

**Issue by WGS-note** [rany2/edge-tts#258]
hello，Ask a question，How many tones can be supported?

**Comment by rany2** [comment]
What does tones mean? Do you mean voices? If yes, then take a look at https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4

In total, it supports 318 voices.

**Comment by WGS-note** [comment]
Yes, thank you for your reply! May I ask how many Chinese voices there are roughly?

Thanks again for your reply!

**Comment by rany2** [comment]
14
