### ISSUE TITLE
pls support more outputFormat Riff22050Hz16BitMonoPcm, Riff24Khz16BitMonoPcm, and not just mp3?

### ISSUE THREAD

**Issue by bestlee666** [rany2/edge-tts#263]
"Can it support more output formats, such as Riff16Khz16KbpsMonoSiren, Riff22050Hz16BitMonoPcm, Riff24Khz16BitMonoPcm, and not just mp3?"

  "outputFormat":"audio-24khz-48kbitrate-mono-mp3"

**Comment by rany2** [comment]
Microsoft is already trying to block this and adding features not supported by Microsoft Edge itself will only make things worse. For this reason, it cannot be done.

**Comment by AJolly** [comment]
Is audio-24khz-48kbitrate-mono-mp3 the best edge supports?  Azure sure supports more  choices, but not sure if edge does.  https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechsynthesisoutputformat?view=azure-dotnet

**Comment by rany2** [comment]
I don't want to risk making it extremely trivial for Microsoft to block edge-tts. All output formats besides mp3 and webm are blocked already. WebM was only used on Linux before Microsoft dropped read aloud support on that platform.

**Comment by AJolly** [comment]
Oh interesting, thats probably why sometimes I notice the audio seems to drop to a lower quality output version
