### ISSUE TITLE
Suddenly unable to use, and the following error message appears，Please help me answer it. Thank you

### ISSUE THREAD

**Issue by changingshow** [rany2/edge-tts#264]
File "C:\xxxxxxxxxxx\lib\site-packages\aiohttp\client.py", line 947, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=xxxxxxxxxxxxxxxxxx&ConnectionId=xxxxxxxxxxxxxxxxxxxx'

**Comment by rany2** [comment]
Can't reproduce, probably an issue with their servers at the moment. Without more information, I'll have to keep this closed.

**Comment by FURYFOR** [comment]
I had the same problem
