### ISSUE TITLE
Can't you make this into module? I'm not really pro with Python and I'm having hard time figure it out how to use this 

### ISSUE THREAD

**Issue by rifkyashari** [rany2/edge-tts#27]

**Comment by rany2** [comment]
It's already a module, have a look at example projects that make use of edge-tts and how they implemented it. It's the last section in the README, https://github.com/rany2/edge-tts/tree/master#python-module.

Simplest example is https://github.com/rany2/edge-tts/blob/master/examples/input_example.py
