### ISSUE TITLE
WSServerHandshakeError

### ISSUE THREAD

**Issue by sixwww** [rany2/edge-tts#274]
from 2024.10.18 use edge_tts raise error
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=2ca2278f39ec4cf59732e7685eecdeeb')

**Comment by LeeQixian** [comment]
update to the 6.1.13 version, or update the User Agent manually
昨天已经有个403的issue了，改UA解决了，更新一下版本，或者pip卸载了然后重新安装都行。

**Comment by rany2** [comment]
Update to 6.1.14 as that also includes a fix for the list_voices method.

**Comment by czght** [comment]
pip install edge-tts==6.1.13  更新到6.1.13，或者卸载再安装
