### ISSUE TITLE
Seem it doesn't work now

### ISSUE THREAD

**Issue by wuzimi** [rany2/edge-tts#275]
It worked well several days ago. But now...

C:\Users\Administrator\tool\EdgeTTS>python test02.py
Traceback (most recent call last):
_ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=9eb612b560754d999f2cd1de0eb0507d'

**Comment by rany2** [comment]
Update to at least version 6.1.14. This issue is already fixed.
