### ISSUE TITLE
I upgraded to version 6.1.14, but it seems that IPs from mainland China are still unable to use it.

### ISSUE THREAD

**Issue by Leowolf93** [rany2/edge-tts#277]
Hello, author. I have upgraded to the latest version 6.1.14, but when using a Chinese IP, I get the following error:

`Traceback (most recent call last):
  File "main.py", line 22, in <module>
  File "asyncio\\runners.py", line 194, in run
  File "asyncio\\runners.py", line 118, in run
  File "asyncio\\base_events.py", line 687, in run_until_complete
  File "main.py", line 9, in main
  File "edge_tts\\communicate.py", line 523, in save
  File "edge_tts\\communicate.py", line 506, in stream
  File "edge_tts\\communicate.py", line 365, in __stream
  File "aiohttp\\client.py", line 1197, in __aenter__
  File "aiohttp\\client.py", line 851, in _ws_connect

aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status',
url=URL('wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=3096e84dce414134891083872c61e459')

[31248] Failed to execute script 'main' due to unhandled exception!`

But if I use a VPN, the issue disappears. It seems to only occur with IPs from mainland China. I am available to assist with testing at any time.

**Comment by rany2** [comment]
Please check if you upgraded edge-tts properly. What is the output of `edge_tts.__version__`?

**Comment by binarrii** [comment]
I'm in mainland China, it works well after upgrade to version `6.1.14`

**Comment by yl17104265** [comment]
I upgraded the version from 6.1.12 to 6.1.14 and it works fine, Beijing IP

**Comment by rany2** [comment]
Probably a similar case to https://github.com/rany2/edge-tts/issues/276#issuecomment-2425421464

Closing...

**Comment by Leowolf93** [comment]
> Please check if you upgraded edge-tts properly. What is the output of `edge_tts.__version__`?

print(edge_tts.__version__)
6.1.14

**Comment by rany2** [comment]
Are you sure it's the same venv?

**Comment by Leowolf93** [comment]
> 你确定这是同一个 venv 吗？



> Are you sure it's the same venv?

I'm terribly sorry, it seems the issue was caused by my environment, and I'm not very proficient with Python. Your update has perfectly fixed the problem. I apologize again for my oversight and for taking up your time.

**Comment by rany2** [comment]
No worries, thanks for confirming! :)

**Comment by davidstarpro-pixel** [comment]
I have tts 7.2.0:
G:\ApplioV3.6.0>env\python -m pip install edge_tts
Requirement already satisfied: edge_tts in g:\appliov3.6.0\env\lib\site-packages (7.2.0)
but...same error Applio: 
RuntimeError: An error occurred loading the audio: Error opening 'G:\\ApplioV3.6.0\\assets\\audios\\tts_output.wav': Format not recognised.
