### ISSUE TITLE
The input example doesn't seem to work on Windows

### ISSUE THREAD

**Issue by Vuizur** [rany2/edge-tts#28]
Hello,

I just realized that the [input example](https://github.com/rany2/edge-tts/blob/master/examples/input_example.py) linked in the README seems to be broken on Windows 10 (in my case Python 3.10.2) due to a [bug in playsound](https://github.com/TaylorSMarks/playsound/issues/121). 

So I think it would make sense to change it to something like this: 

```python
import asyncio
import tempfile
import edge_tts

async def main():
    """
    Main function
    """
    TEXT = "Hello World!"
    VOICE = "en-GB-SoniaNeural"
    OUTPUT_FILE = "test.mp3"

    communicate = edge_tts.Communicate()
    with tempfile.NamedTemporaryFile() as temporary_file:
        async for i in communicate.run(TEXT, voice=VOICE):
            if i[2] is not None:
                temporary_file.write(i[2])
        
            temporary_file.seek(0)
            with open(OUTPUT_FILE, "wb") as f:
                f.write(temporary_file.read())
            

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

(No idea if the code fully makes sense like this, one could probably also do without the tempfile, but at least it works for me.)

**Comment by rany2** [comment]
Hi, that makes sense. I didn't experience the bug because I'm not a Windows user. Though why not open the OUTPUT_FILE from the start? So:

```python3
import asyncio
import edge_tts

async def main():
    """
    Main function
    """
    TEXT = "Hello World!"
    VOICE = "en-GB-SoniaNeural"
    OUTPUT_FILE = "test.mp3"

    communicate = edge_tts.Communicate()
    with open(OUTPUT_FILE, "wb") as f:
        async for i in communicate.run(TEXT, voice=VOICE):
            if i[2] is not None:
                f.write(i[2])

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

**Comment by Vuizur** [comment]
Yes, that is much better. 😅

**Comment by rany2** [comment]
Make a PR so I could merge it :)

**Comment by Vuizur** [comment]
Will do. Should I keep the old example or entirely replace it?

**Comment by rany2** [comment]
Replace it entirely, I don't feel strongly about my usage of playsound.

**Comment by rany2** [comment]
Could be closed now, thanks again for your PR!
