### ISSUE TITLE
Why did I encounter this error when I was executing the batch retrieval of audio files?

### ISSUE THREAD

**Issue by pengpengtao** [rany2/edge-tts#283]
![image](https://github.com/user-attachments/assets/2043cf80-8850-414a-a582-810e938ab309)

**Comment by pengpengtao** [comment]
![image](https://github.com/user-attachments/assets/e34986a6-ed32-4fb0-a1f7-755c738c8c00)
And why do I get this error when scraping audio files

**Comment by rany2** [comment]
Your first error just means you have a DNS/networking issue. Either way it's not an edge-tts issue.

**Comment by pengpengtao** [comment]
> 您的第一个错误仅意味着您遇到了 DNS/网络问题。无论哪种方式，这都不是 edge-tts 问题。

What should I do to avoid this problem?

**Comment by pengpengtao** [comment]
> Your first error just means you have a DNS/networking issue. Either way it's not an edge-tts issue.

Why can't I open some of the audio files I've crawled? Some can be opened.

**Comment by rany2** [comment]
Most likely the ones that can't be opened are empty files with no data.
