### ISSUE TITLE
i get randomly errors, help please

### ISSUE THREAD

**Issue by NeverBeLazyG** [rany2/edge-tts#285]
hi, i get randomly errors even if i am using the same command, it works like 8 of 10 times, 2 times i get this error message. any idea why this happens ?
![image](https://github.com/user-attachments/assets/f3f083c1-66a9-45ef-b150-a6976f095e96)

**Comment by rany2** [comment]
Probably a rate limit. Unfortunately there's no way to differentiate between a rate limit being hit and invalid parameters.
