### ISSUE TITLE
403 error again (only in Mainland China)

### ISSUE THREAD

**Issue by PMPBinZhang** [rany2/edge-tts#286]
您好，更新到6.1.14版本后，运行了一段时间，又出现aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=f80352e338c04c46972b18684bb8635b')这个错误了。

**Comment by ysysdzz** [comment]
same trouble

**Comment by PhilanthropistBright** [comment]
same too

**Comment by jushe** [comment]
same too. And "edge-tts --list-voices" shows jsondecodeError
`Traceback (most recent call last):
  File "/root/miniconda3/bin/edge-tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/edge_tts/util.py", line 136, in main
    asyncio.run(amain())
  File "/root/miniconda3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/edge_tts/util.py", line 118, in amain
    await _print_voices(proxy=args.proxy)
  File "/root/miniconda3/lib/python3.11/site-packages/edge_tts/util.py", line 16, in _print_voices
    voices = await list_voices(proxy=proxy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/edge_tts/list_voices.py", line 33, in list_voices
    data = json.loads(await url.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by huxinyuyeye** [comment]
Me too

**Comment by iorilu** [comment]
seems microsoft changed the service

all people use edge-tts are down now

**Comment by rany2** [comment]
This is happening with the latest version?

**Comment by rany2** [comment]
Also does changing the Chromium version in constants.py fix it again? I don't see this block on my end so it seems like it's China region only.

**Comment by iorilu** [comment]
> This is happening with the latest version?

yes , latest 6.1.14 version

> Also does changing the Chromium version in constants.py fix it again? I don't see this block on my end so it seems like it's China region only.

now version is 129 , should be changed to other number?

**Comment by rany2** [comment]
@iorilu try 130

**Comment by ysysdzz** [comment]
> @iorilu try 130

130 not work

**Comment by rany2** [comment]
I'll see if I can get a hold of a Chinese VPN to test. It's very odd that these blocks are only for China.

**Comment by ifoliage** [comment]
> 我会看看能否找到中国的 VPN 来测试。奇怪的是这些封锁只针对中国。
有可能，只要使用了vpn就能正常使用

**Comment by rany2** [comment]
It's actually surprisingly hard to find a working Chinese proxy. I might try from a Chinese VPS instead.

**Comment by rany2** [comment]
If anybody could help assist with fixing this, it would be appreciated. This seems more complex than the last time given that updating the User-Agent didn't work per @ysysdzz .

**Comment by iorilu** [comment]
does edge-tts work with proxy ?

it seems even if I use proxy , still the same 403 error

**Comment by rany2** [comment]
@iorilu It seems it works fine outside of China. I have no issues.

**Comment by webwlsong** [comment]
me too

**Comment by rany2** [comment]
I just tried from Hong Kong and Taiwan VPNs and they have no problems either. So I guess it's only Mainland China

**Comment by PMPBinZhang** [comment]
![image](https://github.com/user-attachments/assets/2f62a3ce-3d0f-4799-92f1-ef49f7371e9c)
我讲header改成这个，目前是起作用了。

**Comment by rany2** [comment]
@PMPBinZhang can you test if this change works?

```
diff --git a/src/edge_tts/constants.py b/src/edge_tts/constants.py
index 60f8919..86faed7 100644
--- a/src/edge_tts/constants.py
+++ b/src/edge_tts/constants.py
@@ -11,8 +11,8 @@ VOICE_LIST = f"https://{BASE_URL}/voices/list?trustedclienttoken={TRUSTED_CLIENT
 CHROMIUM_MAJOR_VERSION = "129"
 BASE_HEADERS = {
     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
-    f" (KHTML, like Gecko) Chrome/${CHROMIUM_MAJOR_VERSION}.0.0.0 Safari/537.36"
-    f" Edg/${CHROMIUM_MAJOR_VERSION}.0.0.0",
+    f" (KHTML, like Gecko) Chrome/{CHROMIUM_MAJOR_VERSION}.0.0.0 Safari/537.36"
+    f" Edg/{CHROMIUM_MAJOR_VERSION}.0.0.0",
     "Accept-Encoding": "gzip, deflate, br",
     "Accept-Language": "en-US,en;q=0.9",
 }
```

I think a typo was the issue.

**Comment by rany2** [comment]
Please confirm if my fix in master fixes it so I can make a new release.

**Comment by PMPBinZhang** [comment]
ok, I'll try later.

**Comment by rany2** [comment]
I made the release anyway because the old behavior was obviously a bug. If the issue is still happening even with 6.1.15 I'll reopen.

**Comment by amrca** [comment]
> /speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge

**Comment by amrca** [comment]
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>00tAdZwAAAABuHnuiqihYQquVPLtl7knYTEFYRURHRTE3MjEARWRnZQ==

**Comment by rany2** [comment]
@amrca probably just a temporary outage

**Comment by janewu77** [comment]
a few minutes ago I got 403 in old version(6.1.9?).  then upgraded, and It(Version: 6.1.15) works now (in China). FYI

**Comment by amrca** [comment]
this is the pic
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rany2/edge-tts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月27日(星期天) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rany2/edge-tts] 403 error again (only in Mainland China) (Issue #286)





 
a few minutes ago I got 403 in old version(6.1.9?).  then upgraded, and It(Version: 6.1.15) works now (in China). FYI

**Comment by amrca** [comment]
always show the tips


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rany2/edge-tts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月27日(星期天) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rany2/edge-tts] 403 error again (only in Mainland China) (Issue #286)





 
@amrca probably just a temporary outage

**Comment by richardguancn** [comment]
> I made the release anyway because the old behavior was obviously a bug. If the issue is still happening even with 6.1.15 I'll reopen.

still 403 error.

**Comment by wutingkuan** [comment]
still 403 error.

**Comment by rany2** [comment]
Please update to edge-tts version 6.1.16.
