### ISSUE TITLE
Some voices are down

### ISSUE THREAD

**Issue by DTSwink** [rany2/edge-tts#291]
some voices work while some are down, for example "fr-FR-VivienneMultilingualNeural" returns no audio anymore, anyone got info on that ? ;c

**Comment by Creatum** [comment]
Got the same problem with "fr-FR-RemyMultilingualNeural" too. Sometime, it works but most of the time i got an error.

**Comment by rany2** [comment]
Unfortunately I can't do much about these types of things. The service doesn't return any errors when this occurs, just no audio data.

I've seen the official Edge browser also experience this issue so it's not actually unique to edge-tts. You need to press play a couple times for it to work..... monitoring the network traffic you'd see that the service is just returning nothing.
