### ISSUE TITLE
Return Error

### ISSUE THREAD

**Issue by Sdeinf** [rany2/edge-tts#292]
WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response st
atus', url=URL('wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud
/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=44c5aa68925d469d8c3d8cd9a0553e66')

**Comment by rany2** [comment]
Did you update to the latest edge-tts version?

**Comment by Sdeinf** [comment]
Yes, I have already tried it just now

**Comment by rany2** [comment]
So it works now?

**Comment by Sdeinf** [comment]
No, but I found the problem. I need to enable the proxy service to access it. Thank you, buddy.

**Comment by lilaboc** [comment]
still got this issue after upgrade to 6.1.15, it worked for a while, then stopped working again:(

**Comment by rany2** [comment]
@lilaboc I reopened this ticket, you can continue there: https://github.com/rany2/edge-tts/issues/290

check my last posts on it for my response

**Comment by Sdeinf** [comment]
The question again, But I setting mine proxy service and is running successful.   

# add code to edge_tts.Communicate
proxy = 'http://your proxy:port'

![QQ20241031-143905](https://github.com/user-attachments/assets/1ed76c06-3171-4f48-9a6e-cce4fe569db4)

**Comment by Sdeinf** [comment]
The question again, But I setting mine proxy service and is running successful.

add code to edge_tts.Communicate

proxy = 'http://your/ proxy:port'

![QQ20241031-143905](https://github.com/user-attachments/assets/82c39512-6e2f-43ea-860c-d649ce60e8b6)

**Comment by rany2** [comment]
Please update to edge-tts version 6.1.16.
