### ISSUE TITLE
Service is down again

### ISSUE THREAD

**Issue by joseph16388** [rany2/edge-tts#295]
raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=c181d1ece1e54bda85b657d62ca7350c')

**Comment by joseph16388** [comment]
In the end is the code problem, or Microsoft frequently change the interface does not allow use?

**Comment by FURYFOR** [comment]
Setting up the proxy is useful

**Comment by bluechallenge** [comment]
> Setting up the proxy is useful

@FURYFOR May I have more details please? Thanks a lot.

**Comment by PLL-L** [comment]
> 设置代理很有用
请问如何使用？

**Comment by bluechallenge** [comment]
**_Key Configuration_**
macOS - Ventura v13.6.9
VPN Client - ClashX v1.96.2, Proxy Mode - Global
edge-tts - v6.1.15

Here is how the issued was addressed on my laptop, i.e. specify **_proxy_** in _edge_tts.Communicate_ function in my own code. By the way, please update the proxy as per your environment.

communicate = edge_tts.Communicate(story, voice, _proxy="http://127.0.0.1:7890"_)

**Comment by kairyqi** [comment]
> **_Key Configuration_** macOS - Ventura v13.6.9 VPN Client - ClashX v1.96.2, Proxy Mode - Global edge-tts - v6.1.15
> 
> Here is how the issued was addressed on my laptop, i.e. specify **_proxy_** in _edge_tts.Communicate_ function in my own code. By the way, please update the proxy as per your environment.
> 
> communicate = edge_tts.Communicate(story, voice, _proxy="http://127.0.0.1:7890"_)

Finally,it works.Thank you!

**Comment by joseph16388** [comment]
> **_Key Configuration_** macOS - Ventura v13.6.9 VPN Client - ClashX v1.96.2, Proxy Mode - Global edge-tts - v6.1.15
> 
> Here is how the issued was addressed on my laptop, i.e. specify **_proxy_** in _edge_tts.Communicate_ function in my own code. By the way, please update the proxy as per your environment.
> 
> communicate = edge_tts.Communicate(story, voice, _proxy="http://127.0.0.1:7890"_)

Must need a vpn?

**Comment by flyice8** [comment]
In which file or directory is it set?

**Comment by 520131420** [comment]
> In which file or directory is it set?

In your own project, use it directly when invoking
![图片](https://github.com/user-attachments/assets/d8ff7ff2-6e57-48c9-87de-bc790ab8683b)
Or use the command line: edge-tts --text "Hello, world!" --write-media hello.mp3 --write-subtitles hello.vtt --proxy "http://127.0.0.1:{your vpn port} "

**Comment by laraws** [comment]
> > In which file or directory is it set?
> 
> In your own project, use it directly when invoking ![图片](https://private-user-images.githubusercontent.com/89644868/382554353-d8ff7ff2-6e57-48c9-87de-bc790ab8683b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjU0ODUsIm5iZiI6MTczMDYyNTE4NSwicGF0aCI6Ii84OTY0NDg2OC8zODI1NTQzNTMtZDhmZjdmZjItNmU1Ny00OGM5LTg3ZGUtYmM3OTBhYjg2ODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA5MTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNDAzNjYwNTc5MDlhNDAxZGY3NTZjNmFlM2UxOTM3M2IwNmU5NDRhZDZlMDYwMjM2ZmEyNjhlNzAwYmVlZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.66_rnuT7OkGeE0P7UD1mI9eyAE6hFG3bJ5TPUf8E-Dk) Or use the command line: edge-tts --text "Hello, world!" --write-media hello.mp3 --write-subtitles hello.vtt --proxy "[http://127.0.0.1:{your](http://127.0.0.1:%7Byour) vpn port} "

It works. Thank you so much.

**Comment by rany2** [comment]
Please update to edge-tts version 6.1.16.

**Comment by bluechallenge** [comment]
> Please update to edge-tts version 6.1.16.

Thanks @rany2 it works well after updating to v6.1.16.
