### ISSUE TITLE
使用python实时从edge浏览器中抓取最新Sec-MS-GEC的一种方法

### ISSUE THREAD

**Issue by jianchang512** [rany2/edge-tts#299]
如果仅仅是自己本地使用，可以使用 python mitmproxy 模块 监听edge浏览器大声朗读获取 Sec-MS-GEC

基本原理

1.  pip install mitmproxy
2. edge浏览器 中设置 Internal 本地代理地址 127.0.0.1  8080
3. 创建一个本地html文件，里面使用n个p标签创建超长文本，然后js循环每5s将第一段文本移动到末尾，目的是保证可以一直处于朗读中。
4. edge浏览器中手动开启大声朗读，选择一个音色，将语速降到最低
5. 写一个py脚本，捕获wss的url，从中找出 sec，核心代码
``` 

# 保存为 record.py  

from mitmproxy import ctx, http
import urllib.parse
import json
import os

# 目标路径片段，用于检查URL
TARGET_PATH = "/consumer/speech/synthesize/readaloud/edge/v1"

LAST_SEC=""

def request(flow: http.HTTPFlow) -> None:
    global LAST_SEC
    # 检查请求 URL 是否包含目标路径
    if TARGET_PATH in flow.request.path:
        
        # 解析 URL 中的参数
        url = flow.request.pretty_url
        parsed_url = urllib.parse.urlparse(url)
        params = urllib.parse.parse_qs(parsed_url.query)

        # 提取并保存参数
        trusted_token = params.get("TrustedClientToken", [""])[0]
        sec_gec = params.get("Sec-MS-GEC", [""])[0]
        sec_gec_version = params.get("Sec-MS-GEC-Version", [""])[0]
       data={
            "TrustedClientToken":trusted_token,
            "Sec-MS-GEC":sec_gec,
            "Sec-MS-GEC-Version":sec_gec_version
        }
        with open(f"token.json", "w") as f:
            f.write(json.dumps(data))

```
6.  启动监听 `mitmdump -s record.py`

如此可确保实时获取到最新的 sec，如下

![image](https://github.com/user-attachments/assets/7cbbf654-5da1-481a-9682-eac8916a1530)

需要导入mitproxy证书到系统根信任证书，否则无法监听ssl
证书在   C :\Users\用户名\.mitmproxy\mitmproxy-ca-cert.cer

有兴趣的可以照此原理搞个api给大伙用

**Comment by qiqi0308** [comment]
看不太懂咯

**Comment by joseph16388** [comment]
> 如果仅仅是自己本地使用，可以使用 python mitmproxy 模块 监听edge浏览器大声朗读获取 Sec-MS-GEC
> 
> 基本原理
> 
> 1. pip install mitmproxy
> 2. edge浏览器 中设置 Internal 本地代理地址 127.0.0.1  8080
> 3. 创建一个本地html文件，里面使用n个p标签创建超长文本，然后js循环每5s将第一段文本移动到末尾，目的是保证可以一直处于朗读中。
> 4. edge浏览器中手动开启大声朗读，选择一个音色，将语速降到最低
> 5. 写一个py脚本，捕获wss的url，从中找出 sec，核心代码
> 
> ```
> 
> # 保存为 record.py  
> 
> from mitmproxy import ctx, http
> import urllib.parse
> import json
> import os
> 
> # 目标路径片段，用于检查URL
> TARGET_PATH = "/consumer/speech/synthesize/readaloud/edge/v1"
> 
> LAST_SEC=""
> 
> def request(flow: http.HTTPFlow) -> None:
>     global LAST_SEC
>     # 检查请求 URL 是否包含目标路径
>     if TARGET_PATH in flow.request.path:
>         
>         # 解析 URL 中的参数
>         url = flow.request.pretty_url
>         parsed_url = urllib.parse.urlparse(url)
>         params = urllib.parse.parse_qs(parsed_url.query)
> 
>         # 提取并保存参数
>         trusted_token = params.get("TrustedClientToken", [""])[0]
>         sec_gec = params.get("Sec-MS-GEC", [""])[0]
>         sec_gec_version = params.get("Sec-MS-GEC-Version", [""])[0]
>        data={
>             "TrustedClientToken":trusted_token,
>             "Sec-MS-GEC":sec_gec,
>             "Sec-MS-GEC-Version":sec_gec_version
>         }
>         with open(f"token.json", "w") as f:
>             f.write(json.dumps(data))
> ```
> 
> 6. 启动监听 `mitmdump -s record.py`
> 
> 如此可确保实时获取到最新的 sec，如下
> 
> ![image](https://private-user-images.githubusercontent.com/3378335/382697959-7cbbf654-5da1-481a-9682-eac8916a1530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjI1NjksIm5iZiI6MTczMDgyMjI2OSwicGF0aCI6Ii8zMzc4MzM1LzM4MjY5Nzk1OS03Y2JiZjY1NC01ZGExLTQ4MWEtOTY4Mi1lYWM4OTE2YTE1MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTU1NzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFmYzFiM2I1Y2NkYWI0Nzk0OGFjMTJhNTViNDk1OGY1MWJhZDI5ZWFiYTEyNTIxODk3MzM3NjZlYzIwODc2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nQ-b4NQf4o9joxL10dY8TooNG2WneD1U4cFfNJOPzWM)
> 
> 需要导入mitproxy证书到系统根信任证书，否则无法监听ssl 证书在 C :\Users\用户名.mitmproxy\mitmproxy-ca-cert.cer
> 
> 有兴趣的可以照此原理搞个api给大伙用

赞！

**Comment by learnin9** [comment]
`
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>自动循环播放语音</title>
</head>
<body>
    
    <div id="textContainer">
        <p>天王盖地虎，</p>
        <p>宝塔镇河妖。</p>
    </div>

    <script>
        // 获取所有可用的语音
        function getVoices() {
            return new Promise((resolve) => {
                let voices = speechSynthesis.getVoices();
                if (voices.length) {
                    resolve(voices);
                    return;
                }
                speechSynthesis.onvoiceschanged = () => {
                    voices = speechSynthesis.getVoices();
                    resolve(voices);
                };
            });
        }

        // 根据语音名称播放文本并监听结束事件
        async function speakbyvoice(text, voiceName, onEndCallback) {
            const voices = await getVoices();
            const utter = new SpeechSynthesisUtterance(text);
            const voice = voices.find(v => v.name.includes(voiceName));
            if (voice) {
                utter.voice = voice;
            } else {
                console.warn(`找不到语音：${voiceName}`);
            }
            utter.onend = onEndCallback; // 设置播放结束时的回调
            speechSynthesis.speak(utter);
        }

        // 开始循环播放
        function startPlayback() {
            const paragraphs = document.querySelectorAll("#textContainer p");
            let currentParagraphIndex = 0;

            function playNextParagraph() {
                if (currentParagraphIndex >= paragraphs.length) {
                    currentParagraphIndex = 0; // 重置为第一个段落
                }
                const text = paragraphs[currentParagraphIndex].innerText;
                speakbyvoice(text, "Xiaoxiao", playNextParagraph);
                currentParagraphIndex++;
            }

            playNextParagraph(); // 开始播放第一个段落
        }

        // 页面加载完成后自动开始播放
        window.onload = startPlayback;
    </script>
</body>
</html>

`

**Comment by learnin9** [comment]
html代码
```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>自动循环播放语音</title>
</head>
<body>
    <!-- 多行文本显示 -->
    <div id="textContainer">
        <p>天王盖地虎，</p>
        <p>宝塔镇河妖。</p>
    </div>

    <script>
        // 获取所有可用的语音
        function getVoices() {
            return new Promise((resolve) => {
                let voices = speechSynthesis.getVoices();
                if (voices.length) {
                    resolve(voices);
                    return;
                }
                speechSynthesis.onvoiceschanged = () => {
                    voices = speechSynthesis.getVoices();
                    resolve(voices);
                };
            });
        }

        // 根据语音名称播放文本并监听结束事件
        async function speakbyvoice(text, voiceName, onEndCallback) {
            const voices = await getVoices();
            const utter = new SpeechSynthesisUtterance(text);
            const voice = voices.find(v => v.name.includes(voiceName));
            if (voice) {
                utter.voice = voice;
            } else {
                console.warn(`找不到语音：${voiceName}`);
            }
            utter.onend = onEndCallback; // 设置播放结束时的回调
            speechSynthesis.speak(utter);
        }

        // 开始循环播放
        function startPlayback() {
            const paragraphs = document.querySelectorAll("#textContainer p");
            let currentParagraphIndex = 0;

            function playNextParagraph() {
                if (currentParagraphIndex >= paragraphs.length) {
                    currentParagraphIndex = 0; // 重置为第一个段落
                }
                const text = paragraphs[currentParagraphIndex].innerText;
                speakbyvoice(text, "Xiaoxiao", playNextParagraph);
                currentParagraphIndex++;
            }

            playNextParagraph(); // 开始播放第一个段落
        }

        // 页面加载完成后自动开始播放
        window.onload = startPlayback;
    </script>
</body>
</html>
```


python代码
```python
from mitmproxy import ctx, http
import urllib.parse

# 目标路径片段，用于检查URL
TARGET_PATH = "/consumer/speech/synthesize/readaloud/edge/v1"

def request(flow: http.HTTPFlow) -> None:
    # 检查请求 URL 是否包含目标路径
    if TARGET_PATH in flow.request.path:
        
        # 解析 URL 以提取参数
        parsed_url = urllib.parse.urlparse(flow.request.pretty_url)
        params = urllib.parse.parse_qs(parsed_url.query)

        # 提取并打印 `Sec-MS-GEC` 和 `Sec-MS-GEC-Version` 参数
        sec_gec = params.get("Sec-MS-GEC", [""])[0]
        sec_gec_version = params.get("Sec-MS-GEC-Version", [""])[0]

        # 打印结果
        print(f"Sec-MS-GEC: {sec_gec}")
        print(f"Sec-MS-GEC-Version: {sec_gec_version}")
```

python里可以直接async去调用某个自己写的接口，存储数据，然后再开放一个接口，展示此json值即可。

**Comment by rany2** [comment]
Please update to edge-tts version 6.1.16.
