### ISSUE TITLE
When I run "python -m pip install edgeTTS",a error happened

### ISSUE THREAD

**Issue by NineMeowHL** [rany2/edge-tts#3]
ERROR: Could not find a version that satisfies the requirement edgeTTS (from versions: none)
ERROR: No matching distribution found for edgeTTS

The pip version that I used is 20.2.4

**Comment by rany2** [comment]
It's `edge-tts`. Does it work now?

**Comment by rany2** [comment]
I updated the ReadMe so it contains more information. Hopefully that helps! https://github.com/rany2/edge-tts/blob/master/README.md#readme

**Comment by NineMeowHL** [comment]
> It's `edge-tts`. Does it work now?

Yes. Thanks for your help.
