### ISSUE TITLE
'function' object has no attribute 'Communicate 问题

### ISSUE THREAD

**Issue by liuhaozhebj** [rany2/edge-tts#301]
调用这个方法 communicate = edge_tts.Communicate(text, voicename)  
抛出了这么一个异常  'function' object has no attribute 'Communicate 。
我导入进去edge-tts包啦，不知道为什么？ 根本直接原因，应该不是最近的edge-TTS连接不上，不能用问题。

**Comment by liuhaozhebj** [comment]
> 调用这个方法 communicate = edge_tts.Communicate(text, voicename) 抛出了这么一个异常 'function' object has no attribute 'Communicate 。 我导入进去edge-tts包啦，不知道为什么？ 根本直接原因，应该不是最近的edge-TTS连接不上，不能用问题。

**Comment by rany2** [comment]
Do you have a file in called `edge_tts.py`, try to rename it and rerun?
