### ISSUE TITLE
Sec-MS-GEC的API接口地址

### ISSUE THREAD

**Issue by learnin9** [rany2/edge-tts#302]
API接口地址如下：
[http://123.207.46.66:8086/api/getGec](url)

![1730944746906](https://github.com/user-attachments/assets/e1b38dc0-3de5-4321-a597-28b7ad62c030)
大家试试看效果吧。
接口响应在30ms内，Gin的响应速度还是很快的。

**Comment by brightbrightlin10** [comment]
你这是自己写了个浏览器启动程序么。我想自己整个怎么办呢

**Comment by learnin9** [comment]
我是99元/年买个腾讯云主机，windows 2022服务器版本。
然后就可以干活了。：）
代码稳定后，我来开源下。

**Comment by brightbrightlin10** [comment]
> 我是99元/年买个腾讯云主机，windows 2022服务器版本。 然后就可以干活了。：） 代码稳定后，我来开源下。

我利用你在另一个帖子给的代码跑起来了。感谢。我是准备迁移到别的TTS上了。  临时用这个过度很好。感谢

**Comment by zhongtanru** [comment]
过期了

**Comment by learnin9** [comment]
已恢复。

**Comment by zhongtanru** [comment]
太牛了，以后靠你了的代码了。

**Comment by jianchang512** [comment]
期待开源出来，懒得折腾，直接用上跑

除非这个策略针对全球生效，否则看来这2个参数不会加入官方代码了。fork了一份，直接修改了 communicate.py ，这样下游应用无需修改，更新下包就好了   https://github.com/jianchang512/edge-tts

**Comment by yuejunzhang** [comment]
已拦截跨源请求：同源策略禁止读取位于 http://123.207.46.66:8086/api/getGec 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。状态码：200

出现这个错误

**Comment by learnin9** [comment]
已支持。那个59.173.x.x的哥们，你都好几十caps了，轻点，服务器就2核2G。

**Comment by learnin9** [comment]
> 已拦截跨源请求：同源策略禁止读取位于 http://123.207.46.66:8086/api/getGec 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。状态码：200
> 
> 出现这个错误

已支持了。
另外那个59.173.x.x的哥们，你都好几十caps了，轻点，服务器就2核2G。

**Comment by learnin9** [comment]
> > > 已拦截跨源请求：同源策略禁止读取位于 http://123.207.46.66:8086/api/getGec 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。状态码：200
> > > 出现这个错误
> > 
> > 
> > 已支持了。 另外那个59.173.x.x的哥们，你都好几十caps了，轻点，服务器就2核2G。
> 
> 建议搞个域名， 挂到 vercel.app 货 cf上，你这直接服务器ip，肯定扛不住

今晚就把代码整理出来放github上吧。

**Comment by yuejunzhang** [comment]
> > 已拦截跨源请求：同源策略禁止读取位于 http://123.207.46.66:8086/api/getGec 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。状态码：200
> > 出现这个错误
> 
> 已支持了。 另外那个59.173.x.x的哥们，你都好几十caps了，轻点，服务器就2核2G。

多谢！！

**Comment by learnin9** [comment]
https://github.com/learnin9/edgetts-GecAPI

源码已放上去，可以自己搞服务器自己做接口服务了。

**Comment by rany2** [comment]
Please update to edge-tts version 6.1.16.

**Comment by youzihaha** [comment]
> 期待开源出来，懒得折腾，直接用上跑
> 
> 除非这个策略针对全球生效，否则看来这2个参数不会加入官方代码了。fork了一份，直接修改了 communicate.py ，这样下游应用无需修改，更新下包就好了 https://github.com/jianchang512/edge-tts

你好，我拉取了您连接中的项目，按照readme中的提示pip install aiohttp certifi requests 
pip install --upgrade  git+https://github.com/jianchang512/edge-tts#egg=edge-tts                  然后执行edge-tts --text "你好啊朋友们" --voice "zh-CN-YunyangNeural" --write-media hello.mp3  任然报错提示aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=f616754f42754e9c808f1cd0af00f155'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000011CB6331B40>
                      有没有什么办法解决这个问题呢

**Comment by rany2** [comment]
@youzihaha you don't have to use this fork anymore, this was fixed in the main edge-tts.

**Comment by youzihaha** [comment]
> [@youzihaha](https://github.com/youzihaha) you don't have to use this fork anymore, this was fixed in the main edge-tts.

我clone主分支的代码，执行edge-tts --text "Hello, world!" --write-media hello.mp3 --write-subtitles hello.srt命令，还是会报错提示aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=6497107d7c294dabb7f03514c1ca8f97'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D7BDB31B40>

**Comment by rany2** [comment]
@youzihaha Which repo? https://github.com/rany2/edge-tts ?

**Comment by youzihaha** [comment]
> Which repo? https://github.com/rany2/edge-tts ?

是的

**Comment by youzihaha** [comment]
> [@youzihaha](https://github.com/youzihaha) Which repo? https://github.com/rany2/edge-tts ?
使用 pip install --upgrade edge-tts
已经解决该问题，成功生成了音频文件
