### ISSUE TITLE
Streaming text TTS, will it possible?

### ISSUE THREAD

**Issue by jahtim** [rany2/edge-tts#311]
I have an LLM generating ~8 words/sec. i must wait until the text generation is fully complete (~30s)  before i can use edge-tts to get voice.

i do have a workaround , call edge-tts for 3-5 times with small text pieces to reduce latency, but it comes with other problems(concat mp3 with ffmpeg, streaming voice and tone is not smooth )

is it possible to add a 'streaming text' mode? the LLM output is streaming already.

**Comment by rany2** [comment]
It's not possible. You'll either need to send the full text or do it in chunks as you're currently doing.
