### ISSUE TITLE
Licence: Can I integrate Edge-tts into Dify?

### ISSUE THREAD

**Issue by taowang1993** [rany2/edge-tts#313]
Hi Rany2,

I read from the README.md file that Podcastfy integrated Edge-tts.

I wonder what licence is required for integrating Edge-tts.

Is Apache-2.0 acceptable, since Podcastfy is using this licence.

Thank you.

**Comment by rany2** [comment]
Mhm, I might have to relicense to LGPL as I don't think it's technically allowed.

**Comment by rany2** [comment]
I've released edge-tts 6.1.19 which is licensed under LGPLv3.
