### ISSUE TITLE
Submaker doesnt work and idk why

### ISSUE THREAD

**Issue by SlowOnARocketTM** [rany2/edge-tts#336]
i copy pasted the example of the subtitles thing sync or async, both did not work because it coudnt find feed and get_srt

**Comment by rany2** [comment]
You should use the examples from this tree: https://github.com/rany2/edge-tts/tree/e49da2cec54c6476357c08080944155a74e0d9a3

**Comment by rany2** [comment]
SubMaker will change in a future update.

**Comment by zhongtanru** [comment]
if the format changes, the code of  .vtt 2.lrc has to be modified.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zhongtanru** [comment]
The submaker works , but the result is awful. The vtt subtitle made by preview submaker can be shown sentence by sentence , however, the srt subtitle made now is shown word by word, which makes the language learners  mind flash, unable to concentrate on the learning.   I don't think the srt submaker is good.   Can it make sentence by sentence  just like before?


________________________________
发件人: Rany ***@***.***>
发送时间: 2024年12月8日 4:35
收件人: rany2/edge-tts ***@***.***>
抄送: zhongtanru ***@***.***>; Comment ***@***.***>
主题: Re: [rany2/edge-tts] Submaker doesnt work and idk why (Issue #336)


Closed #336<https://github.com/rany2/edge-tts/issues/336> as completed via #342<https://github.com/rany2/edge-tts/pull/342>.

―

**Comment by zhongtanru** [comment]
I have successfully resolved the issue by developing a SRT to LRC conversion function that enables displaying 10 words per line on the screen while playing the MP3.

**Comment by zhongtanru** [comment]
I have successfully resolved the issue by developing a SRT to LRC conversion function that enables displaying 10 words per line on the screen while playing the MP3.
