### ISSUE TITLE
Error while closing mp3 file

### ISSUE THREAD

**Issue by Light-Lens** [rany2/edge-tts#34]
![Screenshot 2023-01-05 215901](https://user-images.githubusercontent.com/73633374/210831002-1db8d7c9-2be9-4bf6-a81e-9d60887ed01f.png)
The section marked in red. I can't fix this issue. I have tried `try except`, still getting the same error.
Please help me fix this. Also it seems that the media player on windows 10 unable to open it.

**Comment by rany2** [comment]
Can you show the code?

**Comment by Light-Lens** [comment]
Yes, here it is:
![Screenshot 2023-01-05 221732](https://user-images.githubusercontent.com/73633374/210834922-c9c6be00-fff2-46b9-84c4-0a43414ff9cc.png)

**Comment by rany2** [comment]
Are you using the latest edge-tts? Also why not use the module?

**Comment by Light-Lens** [comment]
I've tried reinstalling the module but still the same error

**Comment by Light-Lens** [comment]
I've tried reinstalling the module several times so yes, I'm sure I'm using the latest edge-tts.
Also while using the module when my code is:
```python
import asyncio

import edge_tts

TEXT = "Hello World!"
VOICE = "en-US-GuyNeural"
OUTPUT_FILE = "test.mp3"

async def _main() -> None:
    communicate = edge_tts.Communicate(TEXT, VOICE)
    await communicate.save(OUTPUT_FILE)

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(_main())
```

The error I'm getting is:
`C:\Users\SrijanSrivastava\Downloads\test\test.py:41: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(_main())`

**Comment by Light-Lens** [comment]
Yes, I'm using the latest edge-tts. I've tried reinstalling the module several times.
The issue persists even while using the module:
```python
from playsound import playsound
import asyncio, edge_tts

class speak:
    def __init__(self, voice, output):
        self.text, self.voice, self.output = "", voice, output

    def init(self):
        async def _main(text, voice, output) -> None:
            communicate = edge_tts.Communicate(self.text, self.voice)
            await communicate.save(output)

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(_main(self.text, self.output, self.output))

    def say(self, text="Hello World!"):
        self.text = text

        self.init()
        print(self.text)
        playsound(self.output)


speaker = speak("en-US-GuyNeural", "speak.mp3")
speaker.say()
```

**Comment by Light-Lens** [comment]
Hi, thanks for your quick replies. It seems that issue is fixed.
The following code seems to with flawlessly:
```python
from playsound import playsound
import asyncio, edge_tts, os

def Speak(text, voice="en-US-GuyNeural"):
    output = "temp.mp3"

    async def _main(text, voice) -> None:
        communicate = edge_tts.Communicate(text, voice)
        await communicate.save(output)

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(_main(text, voice))

    print(text)
    playsound(output)
    os.remove(output)

Speak("How are you doing!")
```

Thanks for help :)
