### ISSUE TITLE
Wrong subtitles times

### ISSUE THREAD

**Issue by qin20** [rany2/edge-tts#36]
```sh
> edge-tts --text "Hello, world!" --write-media hello.mp3
WEBVTT

00:00:00.100 --> 00:00:01.538
Hello

00:00:00.787 --> 00:00:02.275
world
```

`hello` dones't read so slow and `world` start before `hello` finished

**Comment by rany2** [comment]
It's on purpose. This is a feature, set overlapping to 0 if you want it disabled.

**Comment by rany2** [comment]
The default is now to not have overlapping subtitles. You could have overlapping subtitles by specifying the overlapping parmater to SubMaker (in seconds) or in CLI via `-O <sec.>`.
