### ISSUE TITLE
Added AUR package

### ISSUE THREAD

**Issue by lobroc** [rany2/edge-tts#37]
Hi,

I just wanted to inform that I've created an Arch Linux AUR package here: https://aur.archlinux.org/packages/python-edge-tts
Please let me know if you approve of this, if you'd like me to add you as a co-maintainer on this package, and whether you'd consider adding install instructions (eg. via yay or paru) to the README.
If you see any glaring problems with how I've written it / how I'm installing your package, please let me know.

Thanks!

**Comment by rany2** [comment]
Looks fine, if you want to add me as co-maintainer I'm `rany` on AUR.

**Comment by lobroc** [comment]
Great news! I've added you as a co-maintainer.

**Comment by rany2** [comment]
Thanks for creating the package!
