### ISSUE TITLE
Is it compatible with windows 11?

### ISSUE THREAD

**Issue by ALBI0NE** [rany2/edge-tts#38]
I tried to run it on windows 11, but I get this issue: 
"'edge-tts' is not recognized as an internal or external command, operable program or batch file."

I tried to put it in the PATH, but it didn't resolve the issue.

**Comment by rany2** [comment]
It is compatible with Windows. I'm not sure why you have this issue, maybe your installation of PIP or Python is incomplete?

**Comment by rany2** [comment]
Closing because it's not totally related to edge-tts.

**Comment by 3ternal** [comment]
I got stuck at this as well. Eventually I figured out that you can run it with the command `python -m edge_tts` (note the `_` instead of the `-`).
