### ISSUE TITLE
Adding speaking style to some voices

### ISSUE THREAD

**Issue by saleham5** [rany2/edge-tts#39]
Hey, on[ Microsoft website](https://azure.microsoft.com/en-us/products/cognitive-services/text-to-speech/#overview) they have speaking styles for some voices such as cheerful, happy, and such. is it possible to add these?

**Comment by rany2** [comment]
It used to be possible but it was blocked my Microsoft. Custom SSML is no longer possible and it was removed in 5.x.

**Comment by rany2** [comment]
https://github.com/rany2/edge-tts#custom-ssml

**Comment by saleham5** [comment]
Thank You
