### ISSUE TITLE
It's a new request

### ISSUE THREAD

**Issue by bk111** [rany2/edge-tts#40]
when I run "edge-tts --text "Hello, world!" --write-media hello.mp3", I hope get a hello.vtt and hello.srt in the current dir at the same time. (just like what Whisper do), or at least one of them.

 thanks.

**Comment by rany2** [comment]
just add `--write-subtitles`?

**Comment by rany2** [comment]
I think you want this: `edge-tts --text "Hello, world!" --write-media hello.mp3 --write-subtitles hello.vtt`?

**Comment by bk111** [comment]
> I think you want this: `edge-tts --text "Hello, world!" --write-media hello.mp3 --write-subtitles hello.vtt`?

thanks. It's what I need.
