### ISSUE TITLE
how can i playback the audio in realtime?

### ISSUE THREAD

**Issue by snufas** [rany2/edge-tts#41]
hello,
i want to playback the audio  rather then  save, is there a way to do that?
Thanks

**Comment by rany2** [comment]
On Linux: `edge-tts --text "tts" 2>/dev/null | mpv -` 

For Windows, search about how to pipe stdout to another program.

**Comment by rany2** [comment]
Does it work @snufas ?

**Comment by z0han4eg** [comment]
> On Linux: `edge-tts --text "tts" 2>/dev/null | mpv -`
> 
> For Windows, search about how to pipe stdout to another program (but I think it is `edge-tts --text "tts" 2>nul | mpv -`)

For Windows this will give "[file] Reading from stdin... Failed to recognize file format.". I'm using write-read-clear file ATM.

**Comment by rany2** [comment]
Weird, what if you drop the `2>nul`? Sorry my Windows is rusty..

**Comment by rany2** [comment]
Ah, I think it's because Windows needs to be made aware that the stream is bytes and not text. Otherwise I think it tries to do some weird UTF-16 to UTF-8 conversion and other compatibility tricks.

**Comment by z0han4eg** [comment]
Yea, with 2>$null too. But I don't see any problem writing/reading mp3. With that method MPV will work completely hidden and aloud text imperceptibly. 

I need to receive text from Textractor(clipboard) and use TTS, i.e. aloud subtitles in games. So in case someone will Google Textractor TTS this Powershell code works well with your module:

```
$media_file = "output.mp3"

 while ($true) {
     # Read clipboard text
     $text = Get-Clipboard -Format Text

     if ($text) {
         # Check if clipboard content has changed
         if ($text -ne $last_text) {
             # Speak the text and write media file
             edge-tts --text $text --write-media $media_file | Out-Null
             # Play media file
             mpv $media_file
             # Update last_text to current text
             $last_text = $text
         }
     }
     Start-Sleep -Seconds 1
 }
```

**Comment by rany2** [comment]
@z0han4eg This is a PowerShell issue. See https://github.com/PowerShell/PowerShell/issues/1908 and https://stackoverflow.com/a/63248029/6154099

**Comment by rany2** [comment]
As I suspected, the issue is that it is treating the input as if it were text.

**Comment by z0han4eg** [comment]
Yeap, that's the case. 

This works 
`cmd /c "edge-tts --text "text" | mpv - "`
