### ISSUE TITLE
What's the maximum speed of playback

### ISSUE THREAD

**Issue by Ricksy1024** [rany2/edge-tts#44]
Hello!

Can you please tell me what's the maximum speed of playback? I tried and I can only increase it to +100% speed, is there a way to increase it further? Like Rate="+200%"?
Also, thank you for you work, It's really awesome! Big Respect!

Thanks in advance!

**Comment by rany2** [comment]
Not to my knowledge, if it doesn't do anything at +200% then I presume it doesn't work any further than this. At the end of the day, I'm bound to their API. P.S. why would you want to do +200%, that's triple the normal rate!

**Comment by Ricksy1024** [comment]
Oh I see, thank you for your fast response! Well I'm making my own project and I was curious if I can increase it further haha.
