### ISSUE TITLE
It cannot handle French sentences?

### ISSUE THREAD

**Issue by bk111** [rany2/edge-tts#45]
fr1 = '''Prométhée le lion et l'éléphant.Le lion se "plaignait souvent de" Prométhée, bien que Prométhée l'ait rendu grand et puissant"'''
fr2 = '.' + fr1.replace("'","\'").replace('"','\"') + '.'
os.system(f'edge-tts --voice fr-FR-HenriNeural --text """{fr1}""" --write-media 211.mp3')

考虑以下情况，其中fr1字串的形式有可能是以下几种(既有单引号，又有双引号。而且可能在行首/尾)
Prométhée le lion et l'éléphant.Le
Prométhée le "lion et l'éléphant.Le"
Prométhée le lion et l'éléphant.Le'
"Prométhée le lion" et l'éléphant.Le

**Comment by bk111** [comment]
已经解决！
# fr1 = '''et l'éléphant.Le lion  l'ait. Mais  dit: "Mais j'ai coq." Prométhée a dit: "Pourquoi me raison? Vous." Le lion se cesse , s'est reproché d'être  l'éléphant, et , bavarda. Voyant l'éléphant oreilles, il demanda : " Qu'est-ce  toi ? Pourquoi  oreilles ? " L'éléphant répondit , "Voyez-vous bourdonnants? S'ils , je serai fini." Après cela, le lion réalisa: "Alors  mort?Un  qu'un éléphant. '''
# fr3 = fr1.replace('"','\\"')
# os.system(f"""edge-tts --voice fr-FR-HenriNeural --text "{fr3}" --write-media 4111.mp3""")     -------------这组也ok

**Comment by rany2** [comment]
It can, you just aren't quoting it properly. Just put the text in a file and use --file to save yourself the hassle of quoting (or use the library directly)
