### ISSUE TITLE
Can it also produce .srt subtitle according the comma/period?

### ISSUE THREAD

**Issue by bk111** [rany2/edge-tts#46]
Hi
  thanks the code. It's helpful.
Can you add a new function for it, to produce .srt subtitle according the comma/period/question mark? like, 
1
00:00:00,000 --> 00:00:11,400
美专家称俄亥俄州5到20年后获献大批癌症患者,绿乙烯对身体有哪些危害?美方的应对是否合理?

2
00:00:11,405 --> 00:00:21,200
当地时间3日晚,一列运载危险化学品的火车在美国俄亥俄州脱轨起火,导致危险化学物质绿乙烯泄漏。

**Comment by rany2** [comment]
You cannot
