### ISSUE TITLE
Is it possible to preduce comma and period?

### ISSUE THREAD

**Issue by bk111** [rany2/edge-tts#47]
Is it possible to preduce comma and period?

**Comment by LeninGangwal** [comment]
+1

**Comment by rany2** [comment]
Try putting the text you want to generate in a text file and use the `--file` parameter instead of `--text`.

**Comment by rany2** [comment]
It could generate audio with comma and period for sure and the service actually takes pauses in the generated audio when you do that. So I'm not sure what the issue is about.

**Comment by bk111** [comment]
> It could generate audio with comma and period for sure and the service actually takes pauses in the generated audio when you do that. So I'm not sure what the issue is about.

sorry, I didn't say clearly.  I mean it is possible to produce comma and period in the subtitle (.vtt)? or produce srt/lrc with period/comma at the same time.

**Comment by rany2** [comment]
Unfortunately not. Microsoft doesn't return the text with comma or period so it's just not possible.

**Comment by sweetsmile888** [comment]
> >

what did you do last?

**Comment by sweetsmile888** [comment]
> Unfortunately not. Microsoft doesn't return the text with comma or period so it's just not possible.

do we have any other solution？

**Comment by thanhtoan1196** [comment]
any solution?
