### ISSUE TITLE
What's the limitation length of text? It's ok to read in Edge browser, but it's not in EDGE-tts, warning "The command line is too long."

### ISSUE THREAD

**Issue by bk111** [rany2/edge-tts#48]
Once upon a time there was a rich farmer who had a lot of money, and his fields were all over the farm. But there is one big shortcoming in his happy life, that is, he has no children. When he went to town, he was often ridiculed
    by fellow farmers who asked him why he had no children. At last he couldn't bear it anymore and became very angry. When he got home, he said angrily: "I must have a child, even a hedgehog." So his wife gave birth to a strange child
     with a hedgehog on the upper body and a hedgehog on the lower body. boy. His wife was frightened and complained to him: "Look at you, this is the bad luck you brought." The farmer said helplessly: "The rice has become porridge, wha
    t should I do now? This child has to be baptized, but who can do it?" How about being his godfather?" The wife sighed, "What name should I give him?"Let's call him Hans the Hedgehog."After being baptized, the priest said, "
    He is covered with prickles all over, and he cannot sleep in an ordinary bed." So some hay was spread behind the stove, and Hans the Hedgehog slept on it. His mother could not nurse him because his thorns would hurt her. He lay like
     this behind the stove for eight years, and his father, tired of him, thought to himself, "He might as well be dead!" But he lay there, living tenaciously. There was going to be a market in the city, and before going to the market,
    the farmer asked his wife what she wanted to bring back. "I want some meat and some white bread," she said. Then he asked the maid, who wanted a pair of slippers and some embroidered stockings. Finally he asked the hedgehog, "What d
    o you want, my Hans the hedgehog?" "Dear father," he said, "I want bagpipes." White bread, slippers for the maid, and embroidered stockings, then went behind the stove and gave the bagpipes to Hans the Hedgehog. Hans the Hedgehog to
    ok the bagpipes and said, "Dear father, please go to the blacksmith's shop and shoe the cock. I'm going out on the cock and I won't come back." Hearing this, the father couldn't help but secretly rejoiced. , I thought I could ge
    t rid of him now. He went at once and shod the cock, and Hans the Hedgehog rode off on the cock, taking with him some pigs and asses, which he was going to feed in the forest. They went into the forest, and the big rooster flew him
    up a big tree. After that he stayed in the tree for many, many years, taking care of his donkey and pig until they were brought up, and his father never heard of him. For so many years he was still playing his bagpipes in the trees,
     playing very beautiful music. Once, a king who was lost was passing by, and was surprised when he heard beautiful music, and immediately sent his attendants to find out where the flute was coming from. He looked around, only to fin
    d a small animal high up in a tree that looked like a hedgehog playing on a rooster. So the king ordered his attendants to come forward and ask him why he was sitting there, and whether he knew the way to his kingdom. Hans the Hedge
    hog came down from the tree, and said to the King that he would show the King the way if he would write a pledge that, when he got home, give him the first thing he found in the court. The king thought, "It's easy. Hans the Hedgeho
    g can't read, and he doesn't know what I'm writing anyway." So the King took pen and ink, and wrote a pledge, and when he finished, Hans the Hedgehog showed him the way. , the king returned home safely. His daughter saw it from afar, and ran to meet him with
     great joy, and kissed him happily. Then he thought of Hans the Hedgehog, and told her how it had happened, how he had been compelled to promise to give a gift of the first thing he found upon his return home to a very strange animal which rode like a horse. A
    big rooster, playing beautiful music. But he didn't write what it meant, he wrote that it didn't deserve what it wanted. The princess was very happy when she heard this, and praised her father for what he had done, because it never occurred to her to live wit
    h a hedgehog.Hans the Hedgehog looked after his donkey and pig as usual, and often sat happily in a tree and played on his bagpipes.One day, another king passed by with his entourage and envoys. They also lost their way. The forest was so large and dens
    e that they lost their way home. He also heard the music not far away, so he asked the messenger what it was and ordered him to go and have a look. The messenger went under the tree and saw a cock on the top of the tree, and Hans the Hedgehog was riding on the
    cock's back. The messenger asked him what he was doing up there, "I am letting my donkey and my pigs go. What do you want to do?" The messenger said that they were lost and could not return to their kingdom, and asked him if he could show them the way. Hans th
    e Hedgehog and the Cock came down from the tree, and said to the old King that if the King would give him the first thing he found before the palace, he would tell him the way. The king replied simply: "Yes," and wrote a pledge to Hans the Hedgehog. Then Hans r
    ode ahead on the cock, and showed them the way, and the king returned safely to his kingdom. When he arrived at the courtyard in front of the palace, there was joy there. The King had an only daughter who was very beautiful, and she ran up to meet him, and thre
    w her arms about his neck, and was very glad to have her old father back. She asked where he had been for so long. He told how he had lost his way, and could hardly return, but as he was passing through a great forest, a half-hedgehog, half-human monster riding
     a rooster bagpipe in a high tree pointed out to him and helped him out of the forest, but in return he promised to give him the first thing he met in the court, and now it was she he met first, and the king was very sorry for it.', 'Unexpectedly, the princess
    spoke surprisingly, saying: For the father she loves, she is willing to go with Hans when he comes.Hans the Hedgehog still took good care of his pigs, which grew bigger and bigger until the whole forest was full. So Hans the Hedgehog decided not to live in
    the woods any more, and he sent a message to his father, saying that all the pigpens in the village should be emptied, and that he would drive back a large herd, and invite all who could butcher a pig. His father was very embarrassed when he found out, for he h
    ad always thought that Hans the Hedgehog was dead long ago. Hans the Hedgehog sat comfortably on the back of the rooster, and drove a group of pigs into the village. He gave an order, and the slaughter began. I saw the knife rising and the ax falling, a piece o
    f blood and flesh, and the sound of killing a pig could be heard for miles around! After the matter was over, Hans the Hedgehog said, "Father, please go to the blacksmith's and paw the cock again. This time I will never come back after I leave." Father pawed t
    he cock again, and he felt a burst of relief. , because Hans the Hedgehog is never coming back.Hans the Hedgehog rode the rooster to the first kingdom. The king there ordered that as long as you see a person riding a rooster and holding a bagpipe, everyone
    should raise their bows and arrows, pick up their knives and guns, and block him from outside the palace. So when Hans the Hedgehog came to the gate, they all rushed upon him with their spears raised. He struck the cock with his shoe, and it flew up, over the g
    ate, and landed at the king's window. Hans cried out in a loud voice that the king must keep his promise and give him what was his, or he would kill the king and his daughter. The king was very frightened at this moment, and begged his daughter to go with Hans
    , only in this way could save her own life and her father's life. So she put on all white, and took a six-horse carriage which her father had given her, and a company of beautiful maids, and gold and treasure, and got into the carriage, and put Hans, the cock,
     and the bagpipes in her Beside, and then set off together to leave. The king thought he would never see his daughter again, but he never expected that, not far from the city, Hans the Hedgehog stripped off her beautiful clothes, and then stabbed her bloody wit
    h his thorns. "This is the reward for your hypocrisy and cunning," he said. "Go away, I won't have you." After saying this, he drove her back, and she was despised all her life ever since.Hans the Hedgehog rode on the rooster and played on the bagpipes, an
    d went on to the kingdom of the second king, whom he had shown the way for. The king ordered that anyone who looked like Hans the Hedgehog should salute him, keep him safe, sing long live to him, and lead him to the palace.Unexpectedly, when the king's dau
    ghter saw him, she was startled by his strange appearance. At this time, she warned herself not to change her mind, because she had made a promise to her father. So she came out to meet Hans the Hedgehog, and they became friends for a hundred years. The two wal
    ked to the dining table in the palace, sat down side by side, and enjoyed the delicious food and wine. When evening came, it was time for them to go to bed, but she was afraid of the thorns on his body, and he reassured her that there was no need to be afraid,
    saying that she would not suffer any harm. At the same time, he also asked the old king to send four soldiers to guard the door of the bridal chamber and light a fire. Before he entered the bridal chamber and was about to go to bed, he would crawl out of the he
    dgehog skin and throw the hedgehog skin beside the bed. They were to run there at once, take the hedgehog skin and throw it into the fire, and not leave until it was all gone. When the clock struck eleven o'clock, he stepped into the bridal chamber, took off t
    he hedgehog skin, and threw it beside the bed. The soldier ran over quickly, picked up the hedgehog skin and threw it into the fire. When the fire burned his skin to ashes, he was saved and lay on the bed in a human form, his whole body black as if he had been
    burned by the fire. The king sent a physician, who scrubbed and anointed him with expensive ointments, and soon his skin turned white, and he became a handsome young man. The king's daughter was very happy to see him like this, and they got up happily the next
     morning, and after eating and drinking together, the wedding was held again in a solemn atmosphere, and Hans the Hedgehog succeeded the old king's throne.A few years later he took his wife to see his father and told him that he was his son. But his father
     has repeatedly stated that he has no son, saying that there was one who was born like a prickly hedgehog and left long ago, not knowing where to go. Hans proved who he was, and the old father was delighted, and followed him to his kingdom.

**Comment by rany2** [comment]
Put this in a text file and use `--file`. There is no limit when using the library (it handles splitting automatically)

**Comment by rany2** [comment]
I just wanted to double check and it does in fact work: 
[gh-issue.zip](https://github.com/rany2/edge-tts/files/10855805/a.zip)

**Comment by bk111** [comment]
I'm testing, let you know later

**Comment by bk111** [comment]
1.如果能在vtt里加入标点，就完美了。(不知道能否把输入文本中的标点合并进vtt)。
2.然后再按照有标点的vtt，合并生成半句/全句(以逗号，句号分界)srt/lrc.

vtt转成srt
1.删除 vtt中的WEBVTT
2.vtt中时间轴中的.号换成,号
3.srt中依序加上序号，2条字幕间要空一行
[image: vtt2srt.jpg]

**Comment by bk111** [comment]
--file lengTXT.txt,

it works well.
