### ISSUE TITLE
安装好后无法运行

### ISSUE THREAD

**Issue by acoreq** [rany2/edge-tts#50]
[root@localhost ~]# pip3 install edge-tts
Requirement already satisfied: edge-tts in /usr/local/python3/lib/python3.7/site-packages (6.1.3)
Requirement already satisfied: aiohttp>=3.8.0 in /usr/local/python3/lib/python3.7/site-packages (from edge-tts) (3.8.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (1.8.2)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (4.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (4.0.2)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (3.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (1.3.3)
Requirement already satisfied: asynctest==0.13.0 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (0.13.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/python3/lib/python3.7/site-packages (from aiohttp>=3.8.0->edge-tts) (22.2.0)
Requirement already satisfied: idna>=2.0 in /usr/local/python3/lib/python3.7/site-packages (from yarl<2.0,>=1.0->aiohttp>=3.8.0->edge-tts) (3.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@localhost ~]# edge-tts
bash: edge-tts: command not found...
[root@localhost ~]#

**Comment by rany2** [comment]
You need to include ~/.local/bin to your PATH. If you don't know how to do that either look it up or do `python -m edge_tts` instead.

**Comment by ooking** [comment]
If you're on a Mac, the executable file might be in a folder like this: /Users/yourusername/Library/Python/3.9/bin.
