### ISSUE TITLE
Progress bar for big pdf files

### ISSUE THREAD

**Issue by stringie** [rany2/edge-tts#52]
It would be great if you could add a progress bar as it would be quite useful when sending a big pdf with many pages, say 100+

The program currently eventually terminates successfully if you wait long enough but I'd like to know how long there is to wait.

**Comment by rany2** [comment]
I don't think it's possible. The service sends the audio stream first and then the word boundaries which means I can't even provide a rough estimate. Also the audio stream is sent without any metadata, so there is no information alongside it either.

If you could figure something out that I might have overlooked, feel free to reopen but for now I'll close as not planned.

**Comment by rany2** [comment]
Workaround idea: what you could do is send the text to edge-tts by page/subsection/paragraph/whatever instead of the entire file at once. So you could generate your own estimate that way

**Comment by stringie** [comment]
Yes, I thought of that but I decided to ask you first for a proper progress bar implementation if one could be done.
I suppose that's what I'll be doing now if you say it's likely not possible to do it internally.

**Comment by stringie** [comment]
Yes, I thought of that but I decided to ask you first for a proper progress bar implementation if one could be done.
I suppose that's what I'll be doing now if you say it's likely not possible to do it internally.

**Comment by rany2** [comment]
@stringie something I could do is have it show the current download speed so you could see data is being written and the rate, but of course no ETA. 

Obviously this is not quite a progress bar but it might be acceptable as a compromise I guess.
