### ISSUE TITLE
安装成功，在执行示例时出现『dquote』

### ISSUE THREAD

**Issue by wisinfun** [rany2/edge-tts#53]
Installation successful, 'dquote' error occurred when running the example.
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/41355260/226507363-7e830ee0-fc10-42ec-a404-e4e6a3fc9208.png">

How to deal with this situation, because I am not very familiar with programming and cannot find relevant steps in the instructions. Please provide some guidance.
Operating environment: MacOS 13.2.1 + Python 3.11.2

出现这种情况应该如何处理，因为对编程不是很懂，说明里未发现相关步骤，烦请解答下
运行环境：MacOS 13.2.1 + Python 3.11.2

**Comment by rany2** [comment]
Have a look at this: https://stackoverflow.com/a/65275595/6154099

This is from ZSH not edge-tts. If you want to generate text without worrying about shell quoting/escaping, but the prompt in a text file and use `--file` to read from the file.
