### ISSUE TITLE
Is SSML supported?

### ISSUE THREAD

**Issue by goldengrape** [rany2/edge-tts#58]
May I ask if SSML tags are supported? 
https://cloud.google.com/text-to-speech/docs/ssml
For example, can I use SSML tags to indicate emotions or pauses in the text?

**Comment by rany2** [comment]
https://github.com/rany2/edge-tts#custom-ssml

**Comment by moha-abdi** [comment]
Use this if you need the pauses only: [https://gist.github.com/moha-abdi/8ddbcb206c38f592c65ada1e5479f2bf](url)
