### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by photkey** [rany2/edge-tts#6]
Run `edge-tts --list-voices` command, error message: raise RuntimeError('Event loop is closed')
Running `edge-tts --text "Hello, world!" > hello.mp3` command, the generated MP3 file has no sound.

Windows11
Python 3.8.10

**Comment by rany2** [comment]
Could you try now?

**Comment by photkey** [comment]
Yes, I tried it yesterday and that's it. Now I can continue to try it. What kind of information do I need to provide for troubleshooting?

**Comment by rany2** [comment]
Just update your pip package. I just did a version bump

**Comment by rany2** [comment]
Sorry but could you check for an update again and try 4.0.6?

**Comment by photkey** [comment]
Running `edge-tts --list-voices` normally will not report an error
The mp3 generated by running `edge-tts --text "Hello, world!" > hello.mp3` is still unplayable.

**Comment by photkey** [comment]
> Sorry but could you check for an update again and try 4.0.6?

OK，right now

**Comment by rany2** [comment]
Does it work now?

**Comment by rany2** [comment]
If mp3 still doesn't work can you try instead:

```
edge-tts --write-media hello.mp3 --text "Hello, world"
```

It could be caused by the shell doing something weird, I know Windows does weird things like that

**Comment by photkey** [comment]
Okay, wait a moment for me, I just tried 4.0.5, and I haven't updated to 4.0.6 yet, and the update failed. I'll restart the computer and try again.

**Comment by photkey** [comment]
`edge-tts --text "Hello, world!" > hello.mp3` still cannot play;
`edge-tts --write-media hello.mp3 --text "Hello, world"` finally works, thanks a lot!

**Comment by rany2** [comment]
on 4.0.6?

**Comment by photkey** [comment]
> on 4.0.6?

yes
