### ISSUE TITLE
Is there any way to speed up the process of speech conversion?

### ISSUE THREAD

**Issue by DreamMaoMao** [rany2/edge-tts#61]
What does the speed of language conversion depend on? Is it the performance of the local computer? Is there a way to turn on something like multithreading to convert, such as first breaking down the text into sentences, splitting the text conversion into multiple tasks, and then using multiple threads to convert at the same time, and finally merging the conversion results.

**Comment by rany2** [comment]
The speed is throttled by Microsoft to prevent abuse. In normal cases (like when you're using the Microsoft Edge browser), it will work.

> such as first breaking down the text into sentences

This seems like you're begging them to block your IP, no? In general there are no limits, but I think this is just extremely abusive and won't slide. Currently there are no bans being carried out (unless you do something insane like >5k requests at once, but even that ban lasts for 5 minutes). 

It is technically possible but I don't want to implement it, I'll just get everyone banned and give Microsoft a reason to actively try to ban it. Currently the ~8Mbit/s rate is OK, but I'm open to exploring options if they reduce that speed.

**Comment by rany2** [comment]
On Linux you could do something like `edge-tts --text "your text here" 2>/dev/null | mpv - `. It will stream the output to mpv and you will be able to listen to it instantly. You could do something similar on Windows (on CMD only -- NOT POWERSHELL) like this: `edge-tts --text "your test here" 2>nul | mpv -`

**Comment by DreamMaoMao** [comment]
> On Linux you could do something like `edge-tts --text "your text here" 2>/dev/null | mpv - `. It will stream the output to mpv and you will be able to listen to it instantly. You could do something similar on Windows (on CMD only -- NOT POWERSHELL) like this: `edge-tts --text "your test here" 2>nul | mpv -`

Does the code invocation support this type of data stream output?

**Comment by rany2** [comment]
Yes, if you're asking about whether you could do this in the library it does.

Advanced example of streaming audio with subtitles: https://github.com/rany2/edge-tts/blob/master/examples/streaming_with_subtitles.py
Basic example of streaming audio: https://github.com/rany2/edge-tts/blob/master/examples/basic_audio_streaming.py

**Comment by AIhasArrived** [comment]
> The speed is throttled by Microsoft to prevent abuse. In normal cases (like when you're using the Microsoft Edge browser), it will work.
> 
> > such as first breaking down the text into sentences
> 
> This seems like you're begging them to block your IP, no? In general there are no limits, but I think this is just extremely abusive and won't slide. Currently there are no bans being carried out (unless you do something insane like >5k requests at once, but even that ban lasts for 5 minutes).
> 
> It is technically possible but I don't want to implement it, I'll just get everyone banned and give Microsoft a reason to actively try to ban it. Currently the ~8Mbit/s rate is OK, but I'm open to exploring options if they reduce that speed.

Hello, yoou mention "no limit" ok but do you think the service will stay for life? Are their alternatives, just in case? thanks a lot
