### ISSUE TITLE
SentenceBoundary?

### ISSUE THREAD

**Issue by goldengrape** [rany2/edge-tts#63]
If I want to generate subtitles for the entire sentence, are there any other methods besides WordBoundary? such like SentenceBoundary?

**Comment by rany2** [comment]
Dropped in https://github.com/rany2/edge-tts/commit/797d04f1821df48278222766b5e5214817c6b8e8. From the commit msg:

* Drop SentenceBoundary support (never works properly and too many hacks)
  - No longer actually supported by Azure's official SDK for a few years
    already
