### ISSUE TITLE
customize the output format

### ISSUE THREAD

**Issue by bincooo** [rany2/edge-tts#65]
https://github.com/rany2/edge-tts/blob/1169574ccea1ec7e6f5302697a8a2327f78122eb/src/edge_tts/communicate.py#L352

====
Can I customize the output format of this?
Such as wav ...

**Comment by im-ling** [comment]
according to https://github.com/rany2/edge-tts/issues/57

seems not

**Comment by rany2** [comment]
As @im-ling stated, we can't change the output format too much as Microsoft will ban you. I could experiment a bit to see if they're still banning based on outputFormat but last time I got an error and stopped being able to make requests.
