### ISSUE TITLE
Srt file is not in right format and it generates extra lines

### ISSUE THREAD

**Issue by l3est** [rany2/edge-tts#67]
this is 10.txt's content:
`سلام دوستان، خوش آمدید به کانال آموزش مهاجرت`

and this is the command I'm running:
`edge-tts --voice fa-IR-DilaraNeural --file 10.txt --write-media 10.mp3 --write-subtitle 10.srt --proxy "http://127.0.0.1:5664"`

the audio file is fine but for subtitle I'm getting this (which is invalid when I try to add it in premiere pro):
```WEBVTT



00:00:00.188 --> 00:00:00.475

سلام



00:00:00.575 --> 00:00:01.100

دوستان



00:00:01.163 --> 00:00:01.413

خوش



00:00:01.450 --> 00:00:01.863

آمدید



00:00:01.863 --> 00:00:01.950

به



00:00:01.962 --> 00:00:02.375

کانال



00:00:02.388 --> 00:00:02.750

آموزش



00:00:02.763 --> 00:00:03.450

مهاجرت


```
I enabled "show all characters" in notepad++ so you can see exactly what extra characters are in the file:
![image](https://user-images.githubusercontent.com/8002505/230883098-ae85afdf-123d-45f0-b9b6-b08ba9a31c51.png)

the other issue is srt formatting. an standard srt file looks like this:
```
1
00:05:00,400 --> 00:05:15,300
This is an example of
a subtitle.

2
00:05:16,400 --> 00:05:25,300
This is an example of
a subtitle - 2nd subtitle.
```

edge-tts generates files like this (dots instead of commas for milli seconds and the index before every timestamp):
```
00:05:00.400 --> 00:05:15.300
This is an example of
a subtitle.

00:05:16.400 --> 00:05:25.300
This is an example of
a subtitle - 2nd subtitle.
```

**Comment by rany2** [comment]
That's because it's a WebVTT not a SRT file.

**Comment by l3est** [comment]
my bad 😁 I'll just convert it to srt
