### ISSUE TITLE
Add callback for communicate.save()

### ISSUE THREAD

**Issue by kency** [rany2/edge-tts#69]
some likes after it saved the mp3 file ,i need play it ,or do sth with the mp3 file,so i need write a callback function for #save.finish after save completed
Could u give a callback for communicate.save() ,  some likes  communicate.add_callback.....or  communicate.callback=...

**Comment by rany2** [comment]
Hi, if you add this and make a PR I won't reject it. But I don't get why you'd want to do that versus just:

```python
await save("a.mp3")
do_something_with_mp3("a.mp3")
```

**Comment by kency** [comment]
got it
