### ISSUE TITLE
Request support for subtitle files in SRT format

### ISSUE THREAD

**Issue by photkey** [rany2/edge-tts#7]
Similar applications.
https://voicenotebook.com/srtspeaker.php (Google's text-to-speech is terrible)
https://github.com/bdleavitt/azure-text-to-speech-for-dubbing (might have worked well, but didn't run, no reply from the author)

It would be a lot easier for non-verbal programmers to record some videos for screen recording.I once recorded a 13-minute video and the voiceover consumed four whole days and it was a nightmare.Because it would always say the wrong thing and start again ......
I know this project is already great and supports ssml, but editing ssml is also more time consuming, editing srt can be done very quickly with the help of other subtitle software.

Possible problem: Let's say a sentence in SRT has a timeline of 6 seconds, but using Microsoft Edge's text-to-speech service it takes 8 seconds to actually play the sentence; in this case, you need to automatically adjust the speech speed of the sentence.

**Comment by rany2** [comment]
Interesting idea, I'll give it a shot. Either I'll make a separate program that uses this as a library or add it to the already bundled utility. No idea when I'll manage to do this though

**Comment by photkey** [comment]
Very much looking forward to it!
I've spent days scouring GitHub without finding an ideal project, and so far this project of yours is the best open source project I could find. very much looking forward to your new work!
Wait for the good news!

**Comment by rany2** [comment]
Good news, I've added a subrip to mp3 generator in the examples directory.

This is how to use it:

```
$ ./venv/bin/python3 ./examples/02_subrip_to_mp3.py examples/02_subrip_to_mp3.srt en-US-SaraNeural test.mp3
$ ls -lh test.mp3
-rw------- 1 user user 1.6M Mar 10 12:37 test.mp3
```

**Comment by rany2** [comment]
I realized it is currently slow when dealing multiple hour long SRT. I'll make it a bit faster so it's more usable when you're dealing with that scenario..

**Comment by photkey** [comment]
You're fantastic, the development speed is amazing, I was expecting a long wait ...... I'll try it out right now and get back to you after testing.

**Comment by photkey** [comment]
There are codec issues (srt files are utf-8 encoded) and it doesn't work.
Error message: `UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 49: illegal multibyte sequence`

![Snipaste_2022-03-10_20-37-11](https://user-images.githubusercontent.com/60434581/157664249-4c65da51-fe6d-45f5-b033-606bb9000fdd.png)

**Comment by rany2** [comment]
@photkey Please re-encode it as UTF-8

**Comment by photkey** [comment]
Another suggestion, would it be a little better to read the SRT file and use either of the two SRT libraries below?
https://github.com/cdown/srt
https://github.com/byroot/pysrt

**Comment by rany2** [comment]
Could you try now?

**Comment by photkey** [comment]
> Could you try now?

![image](https://user-images.githubusercontent.com/60434581/157666819-48583b3b-ff4c-4cd9-ac81-68a6508a89b2.png)

**Comment by rany2** [comment]
I've very rarely used Windows so this seems weird especially because you're admin. Do you have any pointers?

Maybe running this without admin could help?

**Comment by rany2** [comment]
What does the Chinese say?

**Comment by photkey** [comment]
> What does the Chinese say?

PermissionError: [WinError 32] Another program is using this file and the process cannot access it. : 'C:\\Users\\tuike\\AppData\\Local\\Temp\\tmpfo2xxsew.mp3'

**Comment by rany2** [comment]
Does it work properly now?

**Comment by photkey** [comment]
Now no errors are reported and it is able to run through, but it does not generate the MP3 file test.mp3.
![image](https://user-images.githubusercontent.com/60434581/157669642-2312a347-6f88-4dea-9d2b-bf6c6248862d.png)

I ran it again and it reported an error near the end.
![image](https://user-images.githubusercontent.com/60434581/157669838-daf14abe-a25b-45c7-81e0-aceafcf85523.png)
In Chinese, it means: the signal timeout has been

**Comment by rany2** [comment]
Do ffmpeg and ffprobe commands work for you?

**Comment by rany2** [comment]
Anyway could you try it again? Maybe on a smaller SRT so it doesn't take too much of your time..

**Comment by photkey** [comment]
Yes, FFmpeg I installed via scoop.
![image](https://user-images.githubusercontent.com/60434581/157670929-8c40e34d-7ae1-4493-874f-97e42dc4cc1f.png)

**Comment by photkey** [comment]
The latest one works fine and generates a playable MP3 file successfully, FFmpeg seems to have some error messages.
![image](https://user-images.githubusercontent.com/60434581/157672171-632e3818-e919-439d-88fb-36b3ad989422.png)

There is one other issue that has a greater impact on effectiveness.
When the time in SRT is less than the text-to-speech time in Microsoft Edge, the speed is automatically adjusted to speed up playback, and this is correct.
When the time in SRT is less than the text-to-speech time in Microsoft Edge, the speed should not be adjusted, and a default speech speed parameter should be used that automatically speeds up only when one of the above situations occurs.

**Comment by rany2** [comment]
> When the time in SRT is more than the text-to-speech time in Microsoft Edge, the speed should not be adjusted, and a default speech speed parameter should be used that automatically speeds up only when one of the above situations occurs.

Essentially you don't want the speed to be slowed down to match the SRT?

**Comment by photkey** [comment]
Yes, because this type of dubbing is mainly used for recorded videos, where you don't need to lip-sync, just finish the words in the corresponding timeline, and it would be weird if the speed of speech is always fast and slow, and it's normal to add subtitles that take longer than the time of speaking.
The times when you need to speed up your speech are, shall we say, compelling; get it wrong here and you can't get the timing right later, so you need to speed it up.

**Comment by photkey** [comment]
To summarize.
1. The default speed of speech can be set.
2. There needs to be automatic speed of speech adjustment, but only acceleration, not deceleration.

**Comment by rany2** [comment]
Is this what you meant? It now uses argparse as well

**Comment by photkey** [comment]
Yes, everything is fine and perfect now.

**Comment by rany2** [comment]
That's very good! I'll bundle it as some kind of extra utility like edge-playback in the future

**Comment by photkey** [comment]
It's a bit of a shame that this is only used as an example of edge-tts, similar paid apps are all the rage in China, even tutorials related to reading text aloud through a Microsoft Edg browser and then recording it with audio recording software are pretty hot.

**Comment by rany2** [comment]
Now standalone, will add a web interface and README to it: https://github.com/rany2/edge-srt-to-speech

You could install with `pip install edge-srt-to-speech`
