### ISSUE TITLE
How do I know the mp3 and its srt/vtt have finished so that I can start to edit the vtt?

### ISSUE THREAD

**Issue by bk111** [rany2/edge-tts#71]

**Comment by bk111** [comment]
How do I know the mp3 and its srt/vtt have finished so that I can start to edit the vtt?

**Comment by rany2** [comment]
I don't understand the question. Wouldn't you know simply when the command is done executing? What's the context of the question, if it's a code issue can you share the snippet that doesn't work?

**Comment by bk111** [comment]
> I don't understand the question. Wouldn't you know simply when the command is done executing? What's the context of the question, if it's a code issue can you share the snippet that doesn't work?

```
os.system(f"""edge-tts 。。。--write-media 1.mp3 --write-subtitles 1.vtt""")
while not os.path.exists(f"{en_mp3_filename_main}.vtt"):   #检测 vtt 文件是否已经完成，如没则循环等待，如有才可以进行下一步?
        time.sleep(1)
copy 1.srt to ....
```
Is the waiting code right?

**Comment by rany2** [comment]
`edge-tts` blocks until it is done, you shouldn't need that loop
