### ISSUE TITLE
c++ version

### ISSUE THREAD

**Issue by jinfagang** [rany2/edge-tts#72]
hello, will there be a c++ version?

**Comment by rany2** [comment]
Not planned but if you're asking about this because the library is slow, it's actually because the connection is throttled by Microsoft. Python is not the bottleneck here.

**Comment by jinfagang** [comment]
@rany2 thank u, not cause of slow, but I wanna integrated it with llama.cpp so that both LLM and tts can work togather. (I didn't found a good Chinese local tts model, so that using microsoft API would be more properly)
