### ISSUE TITLE
Can I use "--text" and multi line text?

### ISSUE THREAD

**Issue by bk111** [rany2/edge-tts#73]
```
a1 = f"""Snow fell on Christmas Eve.
Snow fell on Maisy's house.
Snow fell on Charley's house.
Snow fell on Cyril's house.
Snow fell on Tallulah's house.
Snow fell on Eddie!He was on his way to the Maisy.
"""
os.system(f"""edge-tts --voice en-US-JennyNeural --text "{a1}" --write-media1.mp3 --write-subtitles 1.vtt""")
```

will be broken.  because "--text" can't accept multi line.  How do I fix it with "--text" and feed it multi line text not to create a local file?

**Comment by rany2** [comment]
`--text` does accept multi line. You're sending this data wrong, somehow the shell is eating the line breaks which I think is the case with PowerShell (and maybe Command Prompt, but not sure). Just put this in a text file and save yourself the headache (or use the library, it's fairly basic). 

Actually why aren't you using the library directly? Are the examples not clear enough?
