### ISSUE TITLE
请问这个包是不是只能在windows下允许，centos上可以吗

### ISSUE THREAD

**Issue by hyoutom** [rany2/edge-tts#76]
安装不上
[root@VM-0-9-centos ~]# pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple edge-tts

WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting edge-tts
  Could not find a version that satisfies the requirement edge-tts (from versions: )
No matching distribution found for edge-tts

**Comment by rany2** [comment]
The Python version needs to be at least 3.7. It has been tested by me on Windows and Linux.

**Comment by dingyuan000** [comment]
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple edge-tts
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement edge-tts (from versions: none)
ERROR: No matching distribution found for edge-tts

**Comment by rany2** [comment]
@dingyuan000 any information about the platform?
