### ISSUE TITLE
The sentenceBoundaryEnabled seems not work

### ISSUE THREAD

**Issue by purkylin** [rany2/edge-tts#8]
The wordBoundaryEnabled works. But the sentenceBoundaryEnabled seems not work.

**Comment by purkylin** [comment]
```python
if boundary_type > 0:
    word_boundary = True
if boundary_type > 1:
    sentence_boundary = True
```

If I want use sentence boundary, all should set True.

**Comment by rany2** [comment]
Update to the latest version, `wordBoundaryEnabled` and `sentenceBoundaryEnabled` no longer exist.

You should use boundary type = 2

**Comment by rany2** [comment]
`sentenceBoundaryEnabled` doesn't work properly at Microsoft's end. If it doesn't detect something as a sentence it skips in entirely, right now I have a workaround enabled but let me know if you want the workaround removed.

**Comment by purkylin** [comment]
What does the offset mean If the sample rate is 16000?

The sample output:
```
Meta(type:EdgeTTS.Meta.BoundaryType.sentence, offset: 70625000, duration: nil, text: "Hello World", length: 0)
```

**Comment by rany2** [comment]
I don't think it changes by sample rate. Anyway have a look at the code for the workarounds caused by broken SentenceBoundary ... it's so broken even Microsoft stopped supporting it in their official Azure Cognitive Services offerings

**Comment by rany2** [comment]
I dropped support for SentenceBoundary. Too many hacks to get it to work and Microsoft no longer supports it in their Azure SDK offerings anyway. https://github.com/rany2/edge-tts/commit/797d04f1821df48278222766b5e5214817c6b8e8
