### ISSUE TITLE
i want to play audio from strings directly without saving the mp3 files, how to do it?

### ISSUE THREAD

**Issue by glennford49** [rany2/edge-tts#82]
edge-playback is working on terminal, but i want to play it in python

**Comment by rany2** [comment]
> from strings

you can't but you could stream the audio and get the mp3 data, instead of feeding it into a file here: https://github.com/rany2/edge-tts/blob/master/examples/basic_audio_streaming.py#L28 send it to a library capable of playing back audio from these mp3 chunks
