### ISSUE TITLE
Doubt on edge

### ISSUE THREAD

**Issue by furkanshaikh313** [rany2/edge-tts#97]
Is edge tts able to sing ? If yes please tell how

**Comment by rany2** [comment]
Don't know but it does change its tone depending on the sentence, so maybe if it recognizes its a song it will "sing" it?

**Comment by furkanshaikh313** [comment]
Idk but I want make use of edge -tts for something better in my project can you help me with that?

**Comment by rany2** [comment]
No, this use case won't work
